/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stax;

import java.io.IOException;
import java.io.StringReader;
import java.io.StringWriter;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.stream.XMLEventReader;
import javax.xml.stream.XMLInputFactory;
import javax.xml.stream.events.Attribute;
import javax.xml.stream.events.EndElement;
import javax.xml.stream.events.StartElement;
import javax.xml.stream.events.XMLEvent;
import org.w3c.dom.Node;
import org.xml.sax.InputSource;
import javax.xml.namespace.QName;
import javax.xml.stream.XMLEventFactory;
import javax.xml.stream.XMLOutputFactory;
import javax.xml.stream.XMLStreamConstants;
import javax.xml.stream.XMLStreamReader;
import javax.xml.stream.XMLStreamWriter;

/**
 *
 * @author Ravi.Nistala
 */
public class Stax_Test1 {

    private static final String head1 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
            + "\n"
            + "<!-- The following sample document depicts a fictional characters health summary. Any resemblance to a real person is coincidental. -->";
    private static final String head = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
            + "\n"
            + "<!-- The following sample document depicts a fictional characters health summary. Any resemblance to a real person is coincidental. -->"
            + "<?xml-stylesheet type=\"text/xsl\" href=\"CCD.xsl\"?> ";
    private static final String head2 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
            + "<?xml-stylesheet type=\"text/xsl\" href=\"CCD.xsl\"?> "
            + "<!-- The following sample document depicts a fictional characters health summary. Any resemblance to a real person is coincidental. -->";

    private static final String xmlString = "<ClinicalDocument>\n"
            + "  <typeId extension=\"POCD_HD000040\" root=\"2.16.840.1.113883.1.3\"/>\n"
            + "  <templateId assigningAuthorityName=\"CDA/R2\" root=\"2.16.840.1.113883.3.27.1776\"/>\n"
            + "  <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1\"/>\n"
            + "  <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.1\"/>\n"
            + "  <id extension=\"Laika C32 Test\" assigningAuthorityName=\"Laika: An Open Source EHR Testing Framework projectlaika.org\" root=\"2.16.840.1.113883.3.72\"/>\n"
            + "  <code code=\"34133-9\" displayName=\"Summarization of patient data\" codeSystemName=\"LOINC\" codeSystem=\"2.16.840.1.113883.6.1\"/>\n"
            + "  <title>VA WW TEF #1</title>\n"
            + "  <effectiveTime value=\"20080522100845-0500\"/>\n"
            + "  <confidentialityCode/>\n"
            + "  <languageCode code=\"en-US\"/>\n"
            + "  <recordTarget>\n"
            + "    <patientRole>\n"
            + "      <id extension=\"1234567890\"/>\n"
            + "      <addr>\n"
            + "        <streetAddressLine>1980 Aggrrttooff Court</streetAddressLine>\n"
            + "        <city>Dulles</city>\n"
            + "        <state>VA</state>\n"
            + "        <postalCode>20165</postalCode>\n"
            + "        <country>US</country>\n"
            + "      </addr>\n"
            + "      <telecom value=\"tel:703-555-3311\" use=\"HP\"/>\n"
            + "      <telecom value=\"tel:703-555-2332\" use=\"WP\"/>\n"
            + "      <telecom value=\"mailto:ca@yahoo.com\"/>\n"
            + "      <patient>\n"
            + "        <name>\n"
            + "          <prefix>Mr.</prefix>\n"
            + "          <given qualifier=\"CL\">Cxey</given>\n"
            + "          <family qualifier=\"BR\">Aaaactxy</family>\n"
            + "        </name>\n"
            + "        <administrativeGenderCode code=\"M\" displayName=\"Male\" codeSystemName=\"HL7 AdministrativeGenderCodes\" codeSystem=\"2.16.840.1.113883.5.1\">\n"
            + "          <originalText>AdministrativeGender codes are: M (Male), F (Female) or UN (Undifferentiated).</originalText>\n"
            + "        </administrativeGenderCode>\n"
            + "        <birthTime value=\"19800808\"/>\n"
            + "        <maritalStatusCode code=\"M\" displayName=\"Married\" codeSystemName=\"MaritalStatusCode\" codeSystem=\"2.16.840.1.113883.5.2\"/>\n"
            + "        <religiousAffiliationCode code=\"1013\" displayName=\"Christian\" codeSystemName=\"Religious Affiliation\" codeSystem=\"2.16.840.1.113883.5.1076\"/>\n"
            + "        <languageCommunication>\n"
            + "          <templateId root=\"2.16.840.1.113883.3.88.11.32.2\"/>\n"
            + "          <languageCode code=\"en-US\"/>\n"
            + "          <preferenceInd value=\"false\"/>\n"
            + "        </languageCommunication>\n"
            + "      </patient>\n"
            + "	  <providerOrganization>\n"
            + "				<id root=\"2.16.840.1.113883.1.13.99999\"/>\n"
            + "				<name>Local Community Hospital Organization-2</name>\n"
            + "				<telecom use=\"WP\" value=\"tel:(555) 555-1010\"/>\n"
            + "				<addr use=\"WP\">\n"
            + "					<streetAddressLine>4000 Hospital Dr.</streetAddressLine>\n"
            + "					<city>Portland</city>\n"
            + "					<state>OR</state>\n"
            + "					<postalCode>97005- </postalCode>\n"
            + "					<country>US</country>\n"
            + "				</addr>\n"
            + "			</providerOrganization>\n"
            + "    </patientRole>\n"
            + "  </recordTarget>\n"
            + "  <author>\n"
            + "    <time value=\"20080417\"/>\n"
            + "    <assignedAuthor>\n"
            + "      <id root=\"C320417200800000000001\"/>\n"
            + "      <assignedPerson>\n"
            + "        <name>\n"
            + "        </name>\n"
            + "      </assignedPerson>\n"
            + "      <representedOrganization>\n"
            + "        <id root=\"2.16.840.1.113883.19.5\"/>\n"
            + "        <name>Depertment of Veterans Affairs</name>\n"
            + "      </representedOrganization>\n"
            + "    </assignedAuthor>\n"
            + "  </author>\n"
            + "  <custodian>\n"
            + "    <assignedCustodian>\n"
            + "      <representedCustodianOrganization>\n"
            + "        <id/>\n"
            + "      </representedCustodianOrganization>\n"
            + "    </assignedCustodian>\n"
            + "  </custodian>\n"
            + "  <participant typeCode=\"IND\">\n"
            + "    <templateId root=\"2.16.840.1.113883.3.88.11.32.3\"/>\n"
            + "    <time>\n"
            + "      <low value=\"19990919\"/>\n"
            + "    </time>\n"
            + "    <associatedEntity classCode=\"NOK\">\n"
            + "      <code code=\"WIFE\" displayName=\"Wife\" codeSystemName=\"RoleCode\" codeSystem=\"2.16.840.1.113883.5.111\"/>\n"
            + "      <addr>\n"
            + "        <streetAddressLine>1980 Aggrrttooff Court</streetAddressLine>\n"
            + "        <city>Dulles</city>\n"
            + "        <state>VA</state>\n"
            + "        <postalCode>20165</postalCode>\n"
            + "        <country>US</country>\n"
            + "      </addr>\n"
            + "      <telecom value=\"tel:703-555-1980\" use=\"HP\"/>\n"
            + "      <telecom value=\"tel:703-555-4466\" use=\"WP\"/>\n"
            + "      <telecom value=\"mailto:wja@msn.com\"/>\n"
            + "      <associatedPerson>\n"
            + "        <name>\n"
            + "          <prefix>Mrs.</prefix>\n"
            + "          <given qualifier=\"CL\">Jikkklaan</given>\n"
            + "          <family qualifier=\"BR\">Aaaactxy</family>\n"
            + "        </name>\n"
            + "      </associatedPerson>\n"
            + "    </associatedEntity>\n"
            + "  </participant>\n"
            + "  <documentationOf>\n"
            + "    <serviceEvent classCode=\"PCPR\">\n"
            + "      <effectiveTime>\n"
            + "        <low value=\"0\"/>\n"
            + "        <high value=\"2010\"/>\n"
            + "      </effectiveTime>\n"
            + "      <performer typeCode=\"PRF\">\n"
            + "        <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.4\"/>\n"
            + "        <functionCode code=\"PP\" displayName=\"Primary Care Provider\" codeSystemName=\"Provider Role\" codeSystem=\"2.16.840.1.113883.12.443\">\n"
            + "        </functionCode>\n"
            + "        <time>\n"
            + "          <low value=\"19990707\"/>\n"
            + "        </time>\n"
            + "        <assignedEntity>\n"
            + "          <id/>\n"
            + "          <code code=\"320000000X\" displayName=\"Residential Treatment Facilities\" codeSystemName=\"ProviderCodes\" codeSystem=\"2.16.840.1.113883.6.101\"/>\n"
            + "          <addr>\n"
            + "            <streetAddressLine>5445 Rhhojjkk Blvd</streetAddressLine>\n"
            + "            <streetAddressLine>Suite #6789</streetAddressLine>\n"
            + "            <city>Dulles</city>\n"
            + "            <state>VA</state>\n"
            + "            <postalCode>20165</postalCode>\n"
            + "            <country>US</country>\n"
            + "          </addr>\n"
            + "          <telecom value=\"tel:703-555-8998\" use=\"WP\"/>\n"
            + "          <assignedPerson>\n"
            + "            <name>\n"
            + "              <prefix>Dr.</prefix>\n"
            + "              <given qualifier=\"CL\">Peppplrrr</given>\n"
            + "              <family qualifier=\"BR\">Wdssjhheeem</family>\n"
            + "            </name>\n"
            + "          </assignedPerson>\n"
            + "        </assignedEntity>\n"
            + "      </performer>\n"
            + "    </serviceEvent>\n"
            + "  </documentationOf>\n"
            + "  <component>\n"
            + "    <structuredBody>\n"
            + "      <component>\n"
            + "        <section>\n"
            + "          <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.11\"/>\n"
            + "          <code code=\"11450-4\" displayName=\"Problems\" codeSystemName=\"LOINC\" codeSystem=\"2.16.840.1.113883.6.1\"/>\n"
            + "          <title>Conditions or Problems</title>\n"
            + "          <text>\n"
            + "            <table border=\"1\" width=\"100%\">\n"
            + "              <thead>\n"
            + "                <tr>\n"
            + "                  <th>Problem Name</th>\n"
            + "                  <th>Problem Type</th>\n"
            + "                  <th>Problem Date</th>\n"
            + "                </tr>\n"
            + "              </thead>\n"
            + "              <tbody>\n"
            + "                <tr>\n"
            + "                  <td>\n"
            + "                    <content ID=\"problem-1021520673\">Patient complains of pain in the right foot.</content>\n"
            + "                  </td>\n"
            + "                  <td>Complaint</td>\n"
            + "                  <td>20080215</td>\n"
            + "                </tr>\n"
            + "                <tr>\n"
            + "                  <td>\n"
            + "                    <content ID=\"problem-1021520674\">some discoloration of the skin on right foot/2nd toe.</content>\n"
            + "                  </td>\n"
            + "                  <td>Finding</td>\n"
            + "                  <td>20080215</td>\n"
            + "                </tr>\n"
            + "                <tr>\n"
            + "                  <td>\n"
            + "                    <content ID=\"problem-1021520675\">Roadsie bomb injury.</content>\n"
            + "                  </td>\n"
            + "                  <td>Problem</td>\n"
            + "                  <td>20060101</td>\n"
            + "                </tr>\n"
            + "                <tr>\n"
            + "                  <td>\n"
            + "                    <content ID=\"problem-1021520676\">Prior surgeries to the right leg occurred at several Army Medical Treatment Facilities for shrapnel removal.</content>\n"
            + "                  </td>\n"
            + "                  <td>Finding</td>\n"
            + "                  <td>20060101</td>\n"
            + "                </tr>\n"
            + "                <tr>\n"
            + "                  <td>\n"
            + "                    <content ID=\"problem-1021520677\">X-ray of the right foot shows a radio-opaque fragment overlying the distal 2nd metatarsal bone</content>\n"
            + "                  </td>\n"
            + "                  <td>Finding</td>\n"
            + "                  <td>20080215</td>\n"
            + "                </tr>\n"
            + "                <tr>\n"
            + "                  <td>\n"
            + "                    <content ID=\"problem-1021520678\">309.81-Posttraumatic stress disorder</content>\n"
            + "                  </td>\n"
            + "                  <td>Diagnosis</td>\n"
            + "                  <td>20060101</td>\n"
            + "                </tr>\n"
            + "                <tr>\n"
            + "                  <td>\n"
            + "                    <content ID=\"problem-1021520679\">Surgery advised for collection of the fragment, surrounding tissue and lavage fluid</content>\n"
            + "                  </td>\n"
            + "                  <td>Finding</td>\n"
            + "                  <td>20080217</td>\n"
            + "                </tr>\n"
            + "                <tr>\n"
            + "                  <td>\n"
            + "                    <content ID=\"problem-1021520680\">CPT 20520-Removal of foreign body in muscle or tendon sheath; simple</content>\n"
            + "                  </td>\n"
            + "                  <td>Condition</td>\n"
            + "                  <td>20080307</td>\n"
            + "                </tr>\n"
            + "                <tr>\n"
            + "                  <td>\n"
            + "                    <content ID=\"problem-1021520681\">Urine bio-monitoring kit recommended for home use.</content>\n"
            + "                  </td>\n"
            + "                  <td>Finding</td>\n"
            + "                  <td>20080403</td>\n"
            + "                </tr>\n"
            + "                <tr>\n"
            + "                  <td>\n"
            + "                    <content ID=\"problem-1021520682\">401.1-Hypertension</content>\n"
            + "                  </td>\n"
            + "                  <td>Diagnosis</td>\n"
            + "                  <td>20060101</td>\n"
            + "                </tr>\n"
            + "                <tr>\n"
            + "                  <td>\n"
            + "                    <content ID=\"problem-1021520683\">Foot lump dorsum of the foot just below the 2nd toe</content>\n"
            + "                  </td>\n"
            + "                  <td>Symptom</td>\n"
            + "                  <td>20080215</td>\n"
            + "                </tr>\n"
            + "                <tr>\n"
            + "                  <td>\n"
            + "                    <content ID=\"problem-1021520684\">URINE  Heavy Metal:  Fe 25mg/24h, CU 0.03mg/24h, Pb 0.2mg/24h</content>\n"
            + "                  </td>\n"
            + "                  <td>Finding</td>\n"
            + "                  <td>20080615</td>\n"
            + "                </tr>\n"
            + "              </tbody>\n"
            + "            </table>\n"
            + "          </text>\n"
            + "          <entry>\n"
            + "            <act classCode=\"ACT\" moodCode=\"EVN\">\n"
            + "              <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.27\"/>\n"
            + "              <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.7\"/>\n"
            + "              <id/>\n"
            + "              <code nullFlavor=\"NA\"/>\n"
            + "              <effectiveTime>\n"
            + "                <low value=\"20080215\"/>\n"
            + "                <high nullFlavor=\"UNK\"/>\n"
            + "              </effectiveTime>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.28\"/>\n"
            + "                  <code code=\"409586006\" displayName=\"Complaint\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <text>\n"
            + "                    <reference value=\"#problem-1021520673\"/>\n"
            + "                  </text>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </act>\n"
            + "          </entry>\n"
            + "          <entry>\n"
            + "            <act classCode=\"ACT\" moodCode=\"EVN\">\n"
            + "              <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.27\"/>\n"
            + "              <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.7\"/>\n"
            + "              <id/>\n"
            + "              <code nullFlavor=\"NA\"/>\n"
            + "              <effectiveTime>\n"
            + "                <low value=\"20080215\"/>\n"
            + "                <high nullFlavor=\"UNK\"/>\n"
            + "              </effectiveTime>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.28\"/>\n"
            + "                  <code code=\"404684003\" displayName=\"Finding\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <text>\n"
            + "                    <reference value=\"#problem-1021520674\"/>\n"
            + "                  </text>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </act>\n"
            + "          </entry>\n"
            + "          <entry>\n"
            + "            <act classCode=\"ACT\" moodCode=\"EVN\">\n"
            + "              <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.27\"/>\n"
            + "              <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.7\"/>\n"
            + "              <id/>\n"
            + "              <code nullFlavor=\"NA\"/>\n"
            + "              <effectiveTime>\n"
            + "                <low value=\"20060101\"/>\n"
            + "                <high nullFlavor=\"UNK\"/>\n"
            + "              </effectiveTime>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.28\"/>\n"
            + "                  <code code=\"55607006\" displayName=\"Problem\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <text>\n"
            + "                    <reference value=\"#problem-1021520675\"/>\n"
            + "                  </text>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </act>\n"
            + "          </entry>\n"
            + "          <entry>\n"
            + "            <act classCode=\"ACT\" moodCode=\"EVN\">\n"
            + "              <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.27\"/>\n"
            + "              <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.7\"/>\n"
            + "              <id/>\n"
            + "              <code nullFlavor=\"NA\"/>\n"
            + "              <effectiveTime>\n"
            + "                <low value=\"20060101\"/>\n"
            + "                <high nullFlavor=\"UNK\"/>\n"
            + "              </effectiveTime>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.28\"/>\n"
            + "                  <code code=\"404684003\" displayName=\"Finding\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <text>\n"
            + "                    <reference value=\"#problem-1021520676\"/>\n"
            + "                  </text>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </act>\n"
            + "          </entry>\n"
            + "          <entry>\n"
            + "            <act classCode=\"ACT\" moodCode=\"EVN\">\n"
            + "              <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.27\"/>\n"
            + "              <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.7\"/>\n"
            + "              <id/>\n"
            + "              <code nullFlavor=\"NA\"/>\n"
            + "              <effectiveTime>\n"
            + "                <low value=\"20080215\"/>\n"
            + "                <high nullFlavor=\"UNK\"/>\n"
            + "              </effectiveTime>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.28\"/>\n"
            + "                  <code code=\"404684003\" displayName=\"Finding\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <text>\n"
            + "                    <reference value=\"#problem-1021520677\"/>\n"
            + "                  </text>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </act>\n"
            + "          </entry>\n"
            + "          <entry>\n"
            + "            <act classCode=\"ACT\" moodCode=\"EVN\">\n"
            + "              <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.27\"/>\n"
            + "              <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.7\"/>\n"
            + "              <id/>\n"
            + "              <code nullFlavor=\"NA\"/>\n"
            + "              <effectiveTime>\n"
            + "                <low value=\"20060101\"/>\n"
            + "                <high nullFlavor=\"UNK\"/>\n"
            + "              </effectiveTime>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.28\"/>\n"
            + "                  <code code=\"282291009\" displayName=\"Diagnosis\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <text>\n"
            + "                    <reference value=\"#problem-1021520678\"/>\n"
            + "                  </text>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </act>\n"
            + "          </entry>\n"
            + "          <entry>\n"
            + "            <act classCode=\"ACT\" moodCode=\"EVN\">\n"
            + "              <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.27\"/>\n"
            + "              <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.7\"/>\n"
            + "              <id/>\n"
            + "              <code nullFlavor=\"NA\"/>\n"
            + "              <effectiveTime>\n"
            + "                <low value=\"20080217\"/>\n"
            + "                <high nullFlavor=\"UNK\"/>\n"
            + "              </effectiveTime>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.28\"/>\n"
            + "                  <code code=\"404684003\" displayName=\"Finding\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <text>\n"
            + "                    <reference value=\"#problem-1021520679\"/>\n"
            + "                  </text>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </act>\n"
            + "          </entry>\n"
            + "          <entry>\n"
            + "            <act classCode=\"ACT\" moodCode=\"EVN\">\n"
            + "              <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.27\"/>\n"
            + "              <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.7\"/>\n"
            + "              <id/>\n"
            + "              <code nullFlavor=\"NA\"/>\n"
            + "              <effectiveTime>\n"
            + "                <low value=\"20080307\"/>\n"
            + "                <high nullFlavor=\"UNK\"/>\n"
            + "              </effectiveTime>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.28\"/>\n"
            + "                  <code code=\"64572001\" displayName=\"Condition\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <text>\n"
            + "                    <reference value=\"#problem-1021520680\"/>\n"
            + "                  </text>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </act>\n"
            + "          </entry>\n"
            + "          <entry>\n"
            + "            <act classCode=\"ACT\" moodCode=\"EVN\">\n"
            + "              <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.27\"/>\n"
            + "              <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.7\"/>\n"
            + "              <id/>\n"
            + "              <code nullFlavor=\"NA\"/>\n"
            + "              <effectiveTime>\n"
            + "                <low value=\"20080403\"/>\n"
            + "                <high nullFlavor=\"UNK\"/>\n"
            + "              </effectiveTime>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.28\"/>\n"
            + "                  <code code=\"404684003\" displayName=\"Finding\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <text>\n"
            + "                    <reference value=\"#problem-1021520681\"/>\n"
            + "                  </text>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </act>\n"
            + "          </entry>\n"
            + "          <entry>\n"
            + "            <act classCode=\"ACT\" moodCode=\"EVN\">\n"
            + "              <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.27\"/>\n"
            + "              <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.7\"/>\n"
            + "              <id/>\n"
            + "              <code nullFlavor=\"NA\"/>\n"
            + "              <effectiveTime>\n"
            + "                <low value=\"20060101\"/>\n"
            + "                <high nullFlavor=\"UNK\"/>\n"
            + "              </effectiveTime>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.28\"/>\n"
            + "                  <code code=\"282291009\" displayName=\"Diagnosis\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <text>\n"
            + "                    <reference value=\"#problem-1021520682\"/>\n"
            + "                  </text>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </act>\n"
            + "          </entry>\n"
            + "          <entry>\n"
            + "            <act classCode=\"ACT\" moodCode=\"EVN\">\n"
            + "              <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.27\"/>\n"
            + "              <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.7\"/>\n"
            + "              <id/>\n"
            + "              <code nullFlavor=\"NA\"/>\n"
            + "              <effectiveTime>\n"
            + "                <low value=\"20080215\"/>\n"
            + "                <high nullFlavor=\"UNK\"/>\n"
            + "              </effectiveTime>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.28\"/>\n"
            + "                  <code code=\"418799008\" displayName=\"Symptom\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <text>\n"
            + "                    <reference value=\"#problem-1021520683\"/>\n"
            + "                  </text>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </act>\n"
            + "          </entry>\n"
            + "          <entry>\n"
            + "            <act classCode=\"ACT\" moodCode=\"EVN\">\n"
            + "              <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.27\"/>\n"
            + "              <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.7\"/>\n"
            + "              <id/>\n"
            + "              <code nullFlavor=\"NA\"/>\n"
            + "              <effectiveTime>\n"
            + "                <low value=\"20080615\"/>\n"
            + "                <high nullFlavor=\"UNK\"/>\n"
            + "              </effectiveTime>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.28\"/>\n"
            + "                  <code code=\"404684003\" displayName=\"Finding\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <text>\n"
            + "                    <reference value=\"#problem-1021520684\"/>\n"
            + "                  </text>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </act>\n"
            + "          </entry>\n"
            + "        </section>\n"
            + "      </component>\n"
            + "      <component>\n"
            + "        <section>\n"
            + "          <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.2\"/>\n"
            + "          <code code=\"48765-2\" codeSystem=\"2.16.840.1.113883.6.1\"/>\n"
            + "          <title>Allergies, Adverse Reactions, Alerts</title>\n"
            + "          <text>\n"
            + "            <table border=\"1\" width=\"100%\">\n"
            + "              <thead>\n"
            + "                <tr>\n"
            + "                  <th>Substance</th>\n"
            + "                  <th>Event Type</th>\n"
            + "                  <th>Severity</th>\n"
            + "                </tr>\n"
            + "              </thead>\n"
            + "              <tbody>\n"
            + "                <tr>\n"
            + "                  <td>Lactose</td>\n"
            + "                  <td>Food Allergy</td>\n"
            + "                  <td>\n"
            + "                    <content ID=\"severity-823358887\">Mild</content>\n"
            + "                  </td>\n"
            + "                </tr>\n"
            + "                <tr>\n"
            + "                  <td>Penicillin</td>\n"
            + "                  <td>Drug Allergy</td>\n"
            + "                  <td/>\n"
            + "                </tr>\n"
            + "              </tbody>\n"
            + "            </table>\n"
            + "          </text>\n"
            + "          <entry>\n"
            + "            <act classCode=\"ACT\" moodCode=\"EVN\">\n"
            + "              <templateId root=\"2.16.840.1.113883.10.20.1.27\"/>\n"
            + "              <templateId root=\"2.16.840.1.113883.3.88.11.32.6\"/>\n"
            + "              <id root=\"2C748172-7CC2-4902-8AF0-23A105C4401B\"/>\n"
            + "              <code nullFlavor=\"NA\"/>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId root=\"2.16.840.1.113883.10.20.1.18\"/>\n"
            + "                  <code code=\"414285001\" displayName=\"Food Allergy\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                  <effectiveTime>\n"
            + "                    <low value=\"20061010\"/>\n"
            + "                    <high nullFlavor=\"UNK\"/>\n"
            + "                  </effectiveTime>\n"
            + "                  <participant typeCode=\"CSM\">\n"
            + "                    <participantRole classCode=\"MANU\">\n"
            + "                      <playingEntity classCode=\"MMAT\">\n"
            + "                        <code code=\"\" displayName=\"Lactose\" codeSystemName=\"RxNorm\" codeSystem=\"2.16.840.1.113883.6.88\"/>\n"
            + "                        <name>Lactose</name>\n"
            + "                      </playingEntity>\n"
            + "                    </participantRole>\n"
            + "                  </participant>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </act>\n"
            + "          </entry>\n"
            + "          <entry>\n"
            + "            <act classCode=\"ACT\" moodCode=\"EVN\">\n"
            + "              <templateId root=\"2.16.840.1.113883.10.20.1.27\"/>\n"
            + "              <templateId root=\"2.16.840.1.113883.3.88.11.32.6\"/>\n"
            + "              <id root=\"2C748172-7CC2-4902-8AF0-23A105C4401B\"/>\n"
            + "              <code nullFlavor=\"NA\"/>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId root=\"2.16.840.1.113883.10.20.1.18\"/>\n"
            + "                  <code code=\"416098002\" displayName=\"Drug Allergy\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                  <effectiveTime>\n"
            + "                    <low value=\"19901215\"/>\n"
            + "                    <high nullFlavor=\"UNK\"/>\n"
            + "                  </effectiveTime>\n"
            + "                  <participant typeCode=\"CSM\">\n"
            + "                    <participantRole classCode=\"MANU\">\n"
            + "                      <playingEntity classCode=\"MMAT\">\n"
            + "                        <code code=\"\" displayName=\"Penicillin\" codeSystemName=\"RxNorm\" codeSystem=\"2.16.840.1.113883.6.88\"/>\n"
            + "                        <name>Penicillin</name>\n"
            + "                      </playingEntity>\n"
            + "                    </participantRole>\n"
            + "                  </participant>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </act>\n"
            + "          </entry>\n"
            + "        </section>\n"
            + "      </component>\n"
            + "      <component>\n"
            + "        <section>\n"
            + "          <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.8\"/>\n"
            + "          <code code=\"10160-0\" displayName=\"History of medication use\" codeSystemName=\"LOINC\" codeSystem=\"2.16.840.1.113883.6.1\"/>\n"
            + "          <title>Medications</title>\n"
            + "          <text>\n"
            + "            <table border=\"1\" width=\"100%\">\n"
            + "              <thead>\n"
            + "                <tr>\n"
            + "                  <th>Product Display Name</th>\n"
            + "                  <th>Free Text Brand Name</th>\n"
            + "                  <th>Ordered Value</th>\n"
            + "                  <th>Ordered Unit</th>\n"
            + "                  <th>Expiration Time</th>\n"
            + "                </tr>\n"
            + "              </thead>\n"
            + "              <tbody>\n"
            + "                <tr>\n"
            + "                  <td>\n"
            + "                    <content ID=\"medication-809983340\">Quetiapine 25MG</content>\n"
            + "                  </td>\n"
            + "                  <td/>\n"
            + "                  <td/>\n"
            + "                  <td/>\n"
            + "                  <td/>\n"
            + "                </tr>\n"
            + "                <tr>\n"
            + "                  <td>\n"
            + "                    <content ID=\"medication-809983341\">Lisinopril 20MG</content>\n"
            + "                  </td>\n"
            + "                  <td/>\n"
            + "                  <td/>\n"
            + "                  <td/>\n"
            + "                  <td/>\n"
            + "                </tr>\n"
            + "                <tr>\n"
            + "                  <td>\n"
            + "                    <content ID=\"medication-809983342\">Sertraline 50MG</content>\n"
            + "                  </td>\n"
            + "                  <td/>\n"
            + "                  <td/>\n"
            + "                  <td/>\n"
            + "                  <td/>\n"
            + "                </tr>\n"
            + "              </tbody>\n"
            + "            </table>\n"
            + "          </text>\n"
            + "          <entry>\n"
            + "            <substanceAdministration classCode=\"SBADM\" moodCode=\"EVN\">\n"
            + "              <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.24\"/>\n"
            + "              <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.8\"/>\n"
            + "              <id/>\n"
            + "              <consumable>\n"
            + "                <manufacturedProduct classCode=\"MANU\">\n"
            + "                  <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.53\"/>\n"
            + "                  <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.9\"/>\n"
            + "                  <manufacturedMaterial classCode=\"MMAT\" determinerCode=\"KIND\">\n"
            + "                  </manufacturedMaterial>\n"
            + "                </manufacturedProduct>\n"
            + "              </consumable>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId root=\"2.16.840.1.113883.3.88.11.32.10\"/>\n"
            + "                  <code code=\"73639000\" displayName=\"Prescription Drug\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </substanceAdministration>\n"
            + "          </entry>\n"
            + "          <entry>\n"
            + "            <substanceAdministration classCode=\"SBADM\" moodCode=\"EVN\">\n"
            + "              <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.24\"/>\n"
            + "              <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.8\"/>\n"
            + "              <id/>\n"
            + "              <consumable>\n"
            + "                <manufacturedProduct classCode=\"MANU\">\n"
            + "                  <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.53\"/>\n"
            + "                  <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.9\"/>\n"
            + "                  <manufacturedMaterial classCode=\"MMAT\" determinerCode=\"KIND\">\n"
            + "                  </manufacturedMaterial>\n"
            + "                </manufacturedProduct>\n"
            + "              </consumable>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId root=\"2.16.840.1.113883.3.88.11.32.10\"/>\n"
            + "                  <code code=\"73639000\" displayName=\"Prescription Drug\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </substanceAdministration>\n"
            + "          </entry>\n"
            + "          <entry>\n"
            + "            <substanceAdministration classCode=\"SBADM\" moodCode=\"EVN\">\n"
            + "              <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.24\"/>\n"
            + "              <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.8\"/>\n"
            + "              <id/>\n"
            + "              <consumable>\n"
            + "                <manufacturedProduct classCode=\"MANU\">\n"
            + "                  <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.53\"/>\n"
            + "                  <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.9\"/>\n"
            + "                  <manufacturedMaterial classCode=\"MMAT\" determinerCode=\"KIND\">\n"
            + "                  </manufacturedMaterial>\n"
            + "                </manufacturedProduct>\n"
            + "              </consumable>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId root=\"2.16.840.1.113883.3.88.11.32.10\"/>\n"
            + "                  <code code=\"73639000\" displayName=\"Prescription Drug\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </substanceAdministration>\n"
            + "          </entry>\n"
            + "        </section>\n"
            + "      </component>\n"
            + "    </structuredBody>\n"
            + "  </component>\n"
            + "</ClinicalDocument>";

    private static final String CCRString  = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
            + "<?xml-stylesheet type=\"text/xsl\" href=\"../stylesheet/CCR.xsl\"?>\n"
            + "<!-- edited with XMLSpy v2010 rel. 2 (http://www.altova.com) by Len Gallagher (NIST) -->\n"
            + "<ccr:ContinuityOfCareRecord xsi:schemaLocation=\"urn:astm-org:CCR CCRV1.xsd\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:ccr=\"urn:astm-org:CCR\">\n"
            + " <ccr:CCRDocumentObjectID>CCR_AMBv11_DS01</ccr:CCRDocumentObjectID>\n"
            + " <ccr:Language>\n"
            + "  <ccr:Text>US English</ccr:Text>\n"
            + "  <ccr:Code>\n"
            + "   <ccr:Value>en-US</ccr:Value>\n"
            + "  </ccr:Code>\n"
            + " </ccr:Language>\n"
            + " <ccr:Version>V1.0</ccr:Version>\n"
            + " <ccr:DateTime>\n"
            + "  <ccr:ExactDateTime>2010-03-25T13:15:00-05:00</ccr:ExactDateTime>\n"
            + " </ccr:DateTime>\n"
            + " <ccr:Patient>\n"
            + "  <ccr:ActorID>PatientID_1</ccr:ActorID>\n"
            + " </ccr:Patient>\n"
            + " <ccr:From>\n"
            + "  <ccr:ActorLink>\n"
            + "   <ccr:ActorID>AuthorID_01</ccr:ActorID>\n"
            + "   <ccr:ActorRole>\n"
            + "    <ccr:Text>Personal Physician</ccr:Text>\n"
            + "   </ccr:ActorRole>\n"
            + "  </ccr:ActorLink>\n"
            + " </ccr:From>\n"
            + " <ccr:To>\n"
            + "  <ccr:ActorLink>\n"
            + "   <ccr:ActorID>RecipientID_01</ccr:ActorID>\n"
            + "   <ccr:ActorRole>\n"
            + "    <ccr:Text>Interested Party</ccr:Text>\n"
            + "   </ccr:ActorRole>\n"
            + "  </ccr:ActorLink>\n"
            + " </ccr:To>\n"
            + " <ccr:Purpose>\n"
            + "  <ccr:Description>\n"
            + "   <ccr:Text>Transfer of Care</ccr:Text>\n"
            + "  </ccr:Description>\n"
            + " </ccr:Purpose>\n"
            + " <ccr:Body>\n"
            + "  <ccr:Problems>\n"
            + "   \n"
            + "               <ccr:Problem>\n"
            + "    <ccr:CCRDataObjectID>ProbID_1</ccr:CCRDataObjectID>\n"
            + "    <ccr:DateTime>\n"
            + "     <ccr:ApproximateDateTime>\n"
            + "      <ccr:Text>5/5/06</ccr:Text>\n"
            + "     </ccr:ApproximateDateTime>\n"
            + "    </ccr:DateTime>\n"
            + "    <ccr:Type>\n"
            + "     <ccr:Text>Finding</ccr:Text>\n"
            + "    </ccr:Type>\n"
            + "    <ccr:Description>\n"
            + "     <ccr:Text>Coronary Artery Disease (CAD)</ccr:Text>\n"
            + "     <ccr:Code>\n"
            + "      <ccr:Value>414.01</ccr:Value>\n"
            + "      <ccr:CodingSystem>ICD9-CM</ccr:CodingSystem>\n"
            + "     </ccr:Code>\n"
            + "     <ccr:Code>\n"
            + "      <ccr:Value>53741008</ccr:Value>\n"
            + "      <ccr:CodingSystem>SNOMED CT</ccr:CodingSystem>\n"
            + "     </ccr:Code>\n"
            + "    </ccr:Description>\n"
            + "    <ccr:Status>\n"
            + "     <ccr:Text>Chronic</ccr:Text>\n"
            + "    </ccr:Status>\n"
            + "    <ccr:Source>\n"
            + "     <ccr:Actor>\n"
            + "      <ccr:ActorID>AuthorID_01</ccr:ActorID>\n"
            + "     </ccr:Actor>\n"
            + "    </ccr:Source>\n"
            + "   </ccr:Problem>\n"
            + "   \n"
            + "                         <ccr:Problem>\n"
            + "    <ccr:CCRDataObjectID>ProbID_2</ccr:CCRDataObjectID>\n"
            + "    <ccr:DateTime>\n"
            + "     <ccr:ApproximateDateTime>\n"
            + "      <ccr:Text>5/5/06</ccr:Text>\n"
            + "     </ccr:ApproximateDateTime>\n"
            + "    </ccr:DateTime>\n"
            + "    <ccr:Type>\n"
            + "     <ccr:Text>Symptom</ccr:Text>\n"
            + "    </ccr:Type>\n"
            + "    <ccr:Description>\n"
            + "     <ccr:Text>Hypertension, Essential</ccr:Text>\n"
            + "     <ccr:Code>\n"
            + "      <ccr:Value>401.9</ccr:Value>\n"
            + "      <ccr:CodingSystem>ICD9-CM</ccr:CodingSystem>\n"
            + "     </ccr:Code>\n"
            + "     <ccr:Code>\n"
            + "      <ccr:Value>59621000</ccr:Value>\n"
            + "      <ccr:CodingSystem>SNOMED CT</ccr:CodingSystem>\n"
            + "     </ccr:Code>\n"
            + "    </ccr:Description>\n"
            + "    <ccr:Status>\n"
            + "     <ccr:Text>Active</ccr:Text>\n"
            + "    </ccr:Status>\n"
            + "    <ccr:Source>\n"
            + "     <ccr:Actor>\n"
            + "      <ccr:ActorID>AuthorID_01</ccr:ActorID>\n"
            + "     </ccr:Actor>\n"
            + "    </ccr:Source>\n"
            + "   </ccr:Problem>\n"
            + "  \n"
            + "                        <ccr:Problem>\n"
            + "    <ccr:CCRDataObjectID>ProbID_3</ccr:CCRDataObjectID>\n"
            + "    <ccr:DateTime>\n"
            + "     <ccr:ApproximateDateTime>\n"
            + "      <ccr:Text>12/22/02</ccr:Text>\n"
            + "     </ccr:ApproximateDateTime>\n"
            + "    </ccr:DateTime>\n"
            + "    <ccr:Type>\n"
            + "     <ccr:Text>Diagnosis</ccr:Text>\n"
            + "    </ccr:Type>\n"
            + "    <ccr:Description>\n"
            + "     <ccr:Text>Asthma, unspecified</ccr:Text>\n"
            + "     <ccr:Code>\n"
            + "      <ccr:Value>493.00</ccr:Value>\n"
            + "      <ccr:CodingSystem>ICD9-CM</ccr:CodingSystem>\n"
            + "     </ccr:Code>\n"
            + "     <ccr:Code>\n"
            + "      <ccr:Value>195967001</ccr:Value>\n"
            + "      <ccr:CodingSystem>SNOMED CT</ccr:CodingSystem>\n"
            + "     </ccr:Code>\n"
            + "    </ccr:Description>\n"
            + "    <ccr:Status>\n"
            + "     <ccr:Text>Active</ccr:Text>\n"
            + "    </ccr:Status>\n"
            + "    <ccr:Source>\n"
            + "     <ccr:Actor>\n"
            + "      <ccr:ActorID>AuthorID_01</ccr:ActorID>\n"
            + "     </ccr:Actor>\n"
            + "    </ccr:Source>\n"
            + "   </ccr:Problem>\n"
            + "  \n"
            + "</ccr:Problems>\n"
            + "  \n"
            + "\n"
            + "                 <ccr:Alerts>\n"
            + "   <ccr:Alert>\n"
            + "    <ccr:CCRDataObjectID>AlertID_1</ccr:CCRDataObjectID>\n"
            + "    <ccr:DateTime>\n"
            + "     <ccr:ApproximateDateTime>\n"
            + "      <ccr:Text>6/27/96</ccr:Text>\n"
            + "     </ccr:ApproximateDateTime>\n"
            + "    </ccr:DateTime>\n"
            + "    <ccr:Type>\n"
            + "     <ccr:Text>Drug Allergy</ccr:Text>\n"
            + "     <ccr:Code>\n"
            + "      <ccr:Value>416098002</ccr:Value>\n"
            + "      <ccr:CodingSystem>SNOMED CT</ccr:CodingSystem>\n"
            + "     </ccr:Code>\n"
            + "    </ccr:Type>\n"
            + "    <ccr:Description>\n"
            + "     <ccr:Text>Codeine allergy</ccr:Text>\n"
            + "     <ccr:Code>\n"
            + "      <ccr:Value>293597001</ccr:Value>\n"
            + "      <ccr:CodingSystem>SNOMED CT</ccr:CodingSystem>\n"
            + "     </ccr:Code>\n"
            + "    </ccr:Description>\n"
            + "    <ccr:Status>\n"
            + "     <ccr:Text>Active</ccr:Text>\n"
            + "    </ccr:Status>\n"
            + "    <ccr:Source>\n"
            + "     <ccr:Actor>\n"
            + "      <ccr:ActorID>AuthorID_01</ccr:ActorID>\n"
            + "     </ccr:Actor>\n"
            + "    </ccr:Source>\n"
            + "    <ccr:Agent>\n"
            + "     <ccr:Products>\n"
            + "      <ccr:Product>\n"
            + "       <ccr:CCRDataObjectID/>\n"
            + "       <ccr:Source/>\n"
            + "       <ccr:Product>\n"
            + "        <ccr:ProductName>\n"
            + "         <ccr:Text>Codeine</ccr:Text>\n"
            + "         <ccr:Code>\n"
            + "          <ccr:Value>2670</ccr:Value>\n"
            + "          <ccr:CodingSystem>RxNorm</ccr:CodingSystem>\n"
            + "         </ccr:Code>\n"
            + "        </ccr:ProductName>\n"
            + "       </ccr:Product>\n"
            + "      </ccr:Product>\n"
            + "     </ccr:Products>\n"
            + "    </ccr:Agent>\n"
            + "    <ccr:Reaction>\n"
            + "     <ccr:Description>\n"
            + "      <ccr:Text>Hives, nausea</ccr:Text>\n"
            + "     </ccr:Description>\n"
            + "    </ccr:Reaction>\n"
            + "   </ccr:Alert>\n"
            + "  \n"
            + "   <ccr:Alert>\n"
            + "    <ccr:CCRDataObjectID>AlertID_2</ccr:CCRDataObjectID>\n"
            + "    <ccr:DateTime>\n"
            + "     <ccr:ApproximateDateTime>\n"
            + "      <ccr:Text>3/25/04</ccr:Text>\n"
            + "     </ccr:ApproximateDateTime>\n"
            + "    </ccr:DateTime>\n"
            + "    <ccr:Type>\n"
            + "     <ccr:Text>Drug Allergy</ccr:Text>\n"
            + "     <ccr:Code>\n"
            + "      <ccr:Value>416098002</ccr:Value>\n"
            + "      <ccr:CodingSystem>SNOMED CT</ccr:CodingSystem>\n"
            + "     </ccr:Code>\n"
            + "    </ccr:Type>\n"
            + "    <ccr:Description>\n"
            + "     <ccr:Text>Indomethacin allergy</ccr:Text>\n"
            + "     <ccr:Code>\n"
            + "      <ccr:Value>2943620004</ccr:Value>\n"
            + "      <ccr:CodingSystem>SNOMED CT</ccr:CodingSystem>\n"
            + "     </ccr:Code>\n"
            + "    </ccr:Description>\n"
            + "    <ccr:Status>\n"
            + "     <ccr:Text>Active</ccr:Text>\n"
            + "    </ccr:Status>\n"
            + "    <ccr:Source>\n"
            + "     <ccr:Actor>\n"
            + "      <ccr:ActorID>AuthorID_01</ccr:ActorID>\n"
            + "     </ccr:Actor>\n"
            + "    </ccr:Source>\n"
            + "    <ccr:Reaction>\n"
            + "     <ccr:Description>\n"
            + "      <ccr:Text>Nausea, dizziness, headache</ccr:Text>\n"
            + "     </ccr:Description>\n"
            + "    </ccr:Reaction>\n"
            + "   </ccr:Alert>\n"
            + "  </ccr:Alerts>\n"
            + "  <ccr:Medications>\n"
            + "                          <ccr:Medication>\n"
            + "    <ccr:CCRDataObjectID>MedID_01</ccr:CCRDataObjectID>\n"
            + "    <ccr:DateTime>\n"
            + "     <ccr:ApproximateDateTime>\n"
            + "      <ccr:Text>5/5/2006</ccr:Text>\n"
            + "     </ccr:ApproximateDateTime>\n"
            + "    </ccr:DateTime>\n"
            + "    <ccr:Status>\n"
            + "     <ccr:Text>Active</ccr:Text>\n"
            + "    </ccr:Status>\n"
            + "    <ccr:Source>\n"
            + "     <ccr:Actor>\n"
            + "      <ccr:ActorID>AuthorID_01</ccr:ActorID>\n"
            + "     </ccr:Actor>\n"
            + "    </ccr:Source>\n"
            + "    <ccr:Product>\n"
            + "     <ccr:ProductName>\n"
            + "      <ccr:Text>furosemide</ccr:Text>\n"
            + "      <ccr:Code>\n"
            + "       <ccr:Value>200801</ccr:Value>\n"
            + "       <ccr:CodingSystem>RxNorm</ccr:CodingSystem>\n"
            + "      </ccr:Code>\n"
            + "     </ccr:ProductName>\n"
            + "     <ccr:BrandName>\n"
            + "      <ccr:Text>Lasix</ccr:Text>\n"
            + "     </ccr:BrandName>\n"
            + "     <ccr:Strength>\n"
            + "      <ccr:Value>20</ccr:Value>\n"
            + "      <ccr:Units>\n"
            + "       <ccr:Unit>mg</ccr:Unit>\n"
            + "      </ccr:Units>\n"
            + "     </ccr:Strength>\n"
            + "     <ccr:Form>\n"
            + "      <ccr:Text>Tablet</ccr:Text>\n"
            + "     </ccr:Form>\n"
            + "    </ccr:Product>\n"
            + "    <ccr:Directions>\n"
            + "     <ccr:Direction>\n"
            + "      <ccr:Frequency>\n"
            + "       <ccr:Value>1 tab BID PO</ccr:Value>\n"
            + "      </ccr:Frequency>\n"
            + "     </ccr:Direction>\n"
            + "    </ccr:Directions>\n"
            + "    <ccr:PatientInstructions>\n"
            + "     <ccr:Instruction>\n"
            + "      <ccr:Text>1 tablet by mouth 2 times per day</ccr:Text>\n"
            + "     </ccr:Instruction>\n"
            + "    </ccr:PatientInstructions>\n"
            + "   </ccr:Medication>\n"
            + " \n"
            + "                          <ccr:Medication>\n"
            + "    <ccr:CCRDataObjectID>MedID_02</ccr:CCRDataObjectID>\n"
            + "    <ccr:DateTime>\n"
            + "     <ccr:ApproximateDateTime>\n"
            + "      <ccr:Text>5/5/2006</ccr:Text>\n"
            + "     </ccr:ApproximateDateTime>\n"
            + "    </ccr:DateTime>\n"
            + "    <ccr:Status>\n"
            + "     <ccr:Text>Active</ccr:Text>\n"
            + "    </ccr:Status>\n"
            + "    <ccr:Source>\n"
            + "     <ccr:Actor>\n"
            + "      <ccr:ActorID>AuthorID_01</ccr:ActorID>\n"
            + "     </ccr:Actor>\n"
            + "    </ccr:Source>\n"
            + "    <ccr:Product>\n"
            + "     <ccr:ProductName>\n"
            + "      <ccr:Text>potassium chloride</ccr:Text>\n"
            + "                                                  <ccr:Code>\n"
            + "       <ccr:Value>628958</ccr:Value>\n"
            + "       <ccr:CodingSystem>RxNorm</ccr:CodingSystem>\n"
            + "      </ccr:Code>\n"
            + "     </ccr:ProductName>\n"
            + "     <ccr:BrandName>\n"
            + "      <ccr:Text>Klor-Con</ccr:Text> \n"
            + "     </ccr:BrandName>\n"
            + "     <ccr:Strength>\n"
            + "      <ccr:Value>10</ccr:Value>\n"
            + "      <ccr:Units>\n"
            + "       <ccr:Unit>mEq</ccr:Unit>\n"
            + "      </ccr:Units>\n"
            + "     </ccr:Strength>\n"
            + "     <ccr:Form>\n"
            + "      <ccr:Text>Tablet</ccr:Text>\n"
            + "     </ccr:Form>\n"
            + "    </ccr:Product>\n"
            + "    <ccr:Directions>\n"
            + "     <ccr:Direction>\n"
            + "      <ccr:Frequency>\n"
            + "       <ccr:Value>1 tab BID PO</ccr:Value>\n"
            + "      </ccr:Frequency>\n"
            + "     </ccr:Direction>\n"
            + "    </ccr:Directions>\n"
            + "    <ccr:PatientInstructions>\n"
            + "     <ccr:Instruction>\n"
            + "      <ccr:Text>1 tablet by mouth 2 times per day</ccr:Text>\n"
            + "     </ccr:Instruction>\n"
            + "    </ccr:PatientInstructions>\n"
            + "   </ccr:Medication>\n"
            + "                         <ccr:Medication>\n"
            + "    <ccr:CCRDataObjectID>MedID_03</ccr:CCRDataObjectID>\n"
            + "    <ccr:DateTime>\n"
            + "     <ccr:ApproximateDateTime>\n"
            + "      <ccr:Text>12/22/2002</ccr:Text>\n"
            + "     </ccr:ApproximateDateTime>\n"
            + "    </ccr:DateTime>\n"
            + "    <ccr:Status>\n"
            + "     <ccr:Text>Active</ccr:Text>\n"
            + "    </ccr:Status>\n"
            + "    <ccr:Source>\n"
            + "     <ccr:Actor>\n"
            + "      <ccr:ActorID>AuthorID_01</ccr:ActorID>\n"
            + "     </ccr:Actor>\n"
            + "    </ccr:Source>\n"
            + "    <ccr:Product>\n"
            + "     <ccr:ProductName>\n"
            + "      <ccr:Text>metaproterenol sulfate</ccr:Text>\n"
            + "      <ccr:Code>\n"
            + "       <ccr:Value>206833</ccr:Value>\n"
            + "       <ccr:CodingSystem>RxNorm</ccr:CodingSystem>\n"
            + "      </ccr:Code>\n"
            + "     </ccr:ProductName>\n"
            + "     <ccr:BrandName>\n"
            + "      <ccr:Text>Alupent Inhalation Aerosol</ccr:Text>\n"
            + "     </ccr:BrandName>\n"
            + "     <ccr:Strength>\n"
            + "      <ccr:Value>15</ccr:Value>\n"
            + "      <ccr:Units>\n"
            + "       <ccr:Unit>mg/ml</ccr:Unit>\n"
            + "      </ccr:Units>\n"
            + "     </ccr:Strength>\n"
            + "     <ccr:Form>\n"
            + "      <ccr:Text>puff</ccr:Text>\n"
            + "     </ccr:Form>\n"
            + "    </ccr:Product>\n"
            + "    <ccr:Directions>\n"
            + "     <ccr:Direction>\n"
            + "      <ccr:Dose>\n"
            + "       <ccr:Value>2</ccr:Value>\n"
            + "       <ccr:Units>\n"
            + "        <ccr:Unit>puffs</ccr:Unit>\n"
            + "       </ccr:Units>\n"
            + "      </ccr:Dose>\n"
            + "      <ccr:Route>\n"
            + "       <ccr:Text>Inhaled</ccr:Text>\n"
            + "      </ccr:Route>\n"
            + "      <ccr:Frequency>\n"
            + "       <ccr:Value>Q4h as needed</ccr:Value>\n"
            + "      </ccr:Frequency>\n"
            + "     </ccr:Direction>\n"
            + "    </ccr:Directions>\n"
            + "    <ccr:PatientInstructions>\n"
            + "     <ccr:Instruction>\n"
            + "      <ccr:Text>2 puffs inhaled every 4 hours as needed</ccr:Text>\n"
            + "     </ccr:Instruction>\n"
            + "    </ccr:PatientInstructions>\n"
            + "   </ccr:Medication>\n"
            + " \n"
            + "                </ccr:Medications>\n"
            + " \n"
            + "              <ccr:Results>\n"
            + "     <ccr:Result>\n"
            + "    <ccr:CCRDataObjectID>ResultID_01</ccr:CCRDataObjectID>\n"
            + "    <ccr:DateTime>\n"
            + "     <ccr:ApproximateDateTime>\n"
            + "      <ccr:Text>9/16/09</ccr:Text>\n"
            + "     </ccr:ApproximateDateTime>\n"
            + "    </ccr:DateTime>\n"
            + "    <ccr:Type>\n"
            + "     <ccr:Text>Chemistry</ccr:Text>\n"
            + "    </ccr:Type>\n"
            + "    <ccr:Description>\n"
            + "     <ccr:Text>Potassium</ccr:Text>\n"
            + "     <ccr:Code>\n"
            + "      <ccr:Value>2823-3</ccr:Value>\n"
            + "      <ccr:CodingSystem>LOINC</ccr:CodingSystem>\n"
            + "     </ccr:Code>\n"
            + "    </ccr:Description>\n"
            + "    <ccr:Source>\n"
            + "     <ccr:Actor>\n"
            + "      <ccr:ActorID>AuthorID_01</ccr:ActorID>\n"
            + "     </ccr:Actor>\n"
            + "    </ccr:Source>\n"
            + "    <ccr:Test>\n"
            + "     <ccr:CCRDataObjectID/>\n"
            + "     <ccr:Description>\n"
            + "      <ccr:Text>Potassium</ccr:Text>\n"
            + "      <ccr:Code>\n"
            + "       <ccr:Value>2823-3</ccr:Value>\n"
            + "       <ccr:CodingSystem>LOINC</ccr:CodingSystem>\n"
            + "      </ccr:Code>\n"
            + "     </ccr:Description>\n"
            + "     <ccr:Status>\n"
            + "      <ccr:Text>final result</ccr:Text>\n"
            + "     </ccr:Status>\n"
            + "     <ccr:Source/>\n"
            + "     <ccr:TestResult>\n"
            + "      <ccr:Value>4.3</ccr:Value>\n"
            + "      <ccr:Units>\n"
            + "       <ccr:Unit>mg/dl</ccr:Unit>\n"
            + "      </ccr:Units>\n"
            + "     </ccr:TestResult>\n"
            + "     <ccr:NormalResult>\n"
            + "      <ccr:Normal>\n"
            + "       <ccr:Value>3.5 - 5.3</ccr:Value>\n"
            + "       <ccr:Units>\n"
            + "        <ccr:Unit>mg/dl</ccr:Unit>\n"
            + "       </ccr:Units>\n"
            + "       <ccr:Source/>\n"
            + "      </ccr:Normal>\n"
            + "     </ccr:NormalResult>\n"
            + "    </ccr:Test>\n"
            + "   </ccr:Result>\n"
            + " \n"
            + "\n"
            + "    <ccr:Result>\n"
            + "    <ccr:CCRDataObjectID>ResultID_02</ccr:CCRDataObjectID>\n"
            + "    <ccr:DateTime>\n"
            + "     <ccr:ApproximateDateTime>\n"
            + "      <ccr:Text>9/16/09</ccr:Text>\n"
            + "     </ccr:ApproximateDateTime>\n"
            + "    </ccr:DateTime>\n"
            + "    <ccr:Type>\n"
            + "     <ccr:Text>Chemistry</ccr:Text>\n"
            + "    </ccr:Type>\n"
            + "    <ccr:Description>\n"
            + "     <ccr:Text>Total cholesterol</ccr:Text>\n"
            + "     <ccr:Code>\n"
            + "      <ccr:Value>14647-2</ccr:Value>\n"
            + "      <ccr:CodingSystem>LOINC</ccr:CodingSystem>\n"
            + "     </ccr:Code>\n"
            + "    </ccr:Description>\n"
            + "    <ccr:Source>\n"
            + "     <ccr:Actor>\n"
            + "      <ccr:ActorID>AuthorID_01</ccr:ActorID>\n"
            + "     </ccr:Actor>\n"
            + "    </ccr:Source>\n"
            + "    <ccr:Test>\n"
            + "     <ccr:CCRDataObjectID/>\n"
            + "     <ccr:Description>\n"
            + "      <ccr:Text>Total cholesterol</ccr:Text>\n"
            + "      <ccr:Code>\n"
            + "       <ccr:Value>14647-2</ccr:Value>\n"
            + "       <ccr:CodingSystem>LOINC</ccr:CodingSystem>\n"
            + "      </ccr:Code>\n"
            + "     </ccr:Description>\n"
            + "     <ccr:Status>\n"
            + "      <ccr:Text>final result</ccr:Text>\n"
            + "     </ccr:Status>\n"
            + "     <ccr:Source/>\n"
            + "     <ccr:TestResult>\n"
            + "      <ccr:Value>162</ccr:Value>\n"
            + "      <ccr:Units>\n"
            + "       <ccr:Unit>mg/dl</ccr:Unit>\n"
            + "      </ccr:Units>\n"
            + "     </ccr:TestResult>\n"
            + "     <ccr:NormalResult>\n"
            + "      <ccr:Normal>\n"
            + "       <ccr:Value>&lt; 200</ccr:Value>\n"
            + "       <ccr:Units>\n"
            + "        <ccr:Unit>mg/dl</ccr:Unit>\n"
            + "       </ccr:Units>\n"
            + "       <ccr:Source/>\n"
            + "      </ccr:Normal>\n"
            + "     </ccr:NormalResult>\n"
            + "    </ccr:Test>\n"
            + "   </ccr:Result>\n"
            + "   \n"
            + "            <ccr:Result>\n"
            + "    <ccr:CCRDataObjectID>ResultID_03</ccr:CCRDataObjectID>\n"
            + "    <ccr:DateTime>\n"
            + "     <ccr:ApproximateDateTime>\n"
            + "      <ccr:Text>2/16/10</ccr:Text>\n"
            + "     </ccr:ApproximateDateTime>\n"
            + "    </ccr:DateTime>\n"
            + "    <ccr:Type>\n"
            + "     <ccr:Text>Imaging - X-ray</ccr:Text>\n"
            + "    </ccr:Type>\n"
            + "    <ccr:Description>\n"
            + "     <ccr:Text>Chest X-ray, PA</ccr:Text>\n"
            + "     <ccr:Code>\n"
            + "      <ccr:Value>24648-8</ccr:Value>\n"
            + "      <ccr:CodingSystem>LOINC</ccr:CodingSystem>\n"
            + "     </ccr:Code>     \n"
            + "    </ccr:Description>\n"
            + "    <ccr:Source>\n"
            + "     <ccr:Actor>\n"
            + "      <ccr:ActorID>AuthorID_01</ccr:ActorID>\n"
            + "     </ccr:Actor>\n"
            + "    </ccr:Source>\n"
            + "    <ccr:Test>\n"
            + "     <ccr:CCRDataObjectID/>\n"
            + "     <ccr:Description>\n"
            + "      <ccr:Text>Chest X-ray, PA</ccr:Text>\n"
            + "      <ccr:Code>\n"
            + "       <ccr:Value>24648-8</ccr:Value>\n"
            + "       <ccr:CodingSystem>LOINC</ccr:CodingSystem>\n"
            + "      </ccr:Code>\n"
            + "      \n"
            + "     </ccr:Description>\n"
            + "     <ccr:Status>\n"
            + "      <ccr:Text>final result</ccr:Text>\n"
            + "     </ccr:Status>\n"
            + "     <ccr:Source/>\n"
            + "     <ccr:TestResult>\n"
            + "      <ccr:Description>\n"
            + "       <ccr:Text>Increased bronchial wall markings, patchy infiltrates</ccr:Text>\n"
            + "      </ccr:Description>\n"
            + "     </ccr:TestResult>\n"
            + "    </ccr:Test>\n"
            + "   </ccr:Result>\n"
            + "  </ccr:Results>\n"
            + "  \n"
            + "   \n"
            + " </ccr:Body>\n"
            + " <ccr:Actors>\n"
            + "  <ccr:Actor>\n"
            + "   <ccr:ActorObjectID>PatientID_1</ccr:ActorObjectID>\n"
            + "   <ccr:Person>\n"
            + "    <ccr:Name>\n"
            + "     <ccr:BirthName>\n"
            + "      <ccr:Given>John</ccr:Given>\n"
            + "      <ccr:Given>D.</ccr:Given>\n"
            + "      <ccr:Family>Stuart</ccr:Family>\n"
            + "     </ccr:BirthName>\n"
            + "    </ccr:Name>\n"
            + "    <ccr:DateOfBirth>\n"
            + "     <ccr:ExactDateTime>1953-02-15T11:20:00-05:00</ccr:ExactDateTime>\n"
            + "    </ccr:DateOfBirth>\n"
            + "    <ccr:Gender>\n"
            + "     <ccr:Text>Male</ccr:Text>\n"
            + "     <ccr:Code>\n"
            + "      <ccr:Value>M</ccr:Value>\n"
            + "      <ccr:CodingSystem>HL7 AdministrativeGender</ccr:CodingSystem>\n"
            + "     </ccr:Code>\n"
            + "    </ccr:Gender>\n"
            + "   </ccr:Person>\n"
            + "   <ccr:IDs>\n"
            + "    <ccr:ID>9996799589</ccr:ID>\n"
            + "    <ccr:IssuedBy>\n"
            + "     <ccr:ActorID>ClinicID_01</ccr:ActorID>\n"
            + "     <ccr:ActorRole>\n"
            + "      <ccr:Text>Medical Record Number Generator</ccr:Text>\n"
            + "     </ccr:ActorRole>\n"
            + "    </ccr:IssuedBy>\n"
            + "    <ccr:Source/>\n"
            + "   </ccr:IDs>\n"
            + "   <ccr:Address>\n"
            + "    <ccr:Line1>5739 Hazel Street</ccr:Line1>\n"
            + "    <ccr:City>Williamsport</ccr:City>\n"
            + "    <ccr:State>PA</ccr:State>\n"
            + "    <ccr:PostalCode>17701</ccr:PostalCode>\n"
            + "   </ccr:Address>\n"
            + "   <ccr:Telephone>\n"
            + "    <ccr:Value>+1-570-898-2189</ccr:Value>\n"
            + "   </ccr:Telephone>\n"
            + "   <ccr:Source/>\n"
            + "  </ccr:Actor>\n"
            + "  <ccr:Actor>\n"
            + "   <ccr:ActorObjectID>AuthorID_01</ccr:ActorObjectID>\n"
            + "   <ccr:Person>\n"
            + "    <ccr:Name>\n"
            + "     <ccr:BirthName>\n"
            + "      <ccr:Given>Thomas</ccr:Given>\n"
            + "      <ccr:Family>Henry</ccr:Family>\n"
            + "      <ccr:Suffix>MD</ccr:Suffix>\n"
            + "     </ccr:BirthName>\n"
            + "    </ccr:Name>\n"
            + "   </ccr:Person>\n"
            + "   <ccr:Address>\n"
            + "    <ccr:Line1>5544 Sutter Street</ccr:Line1>\n"
            + "    <ccr:City>Williamsport</ccr:City>\n"
            + "    <ccr:State>PA</ccr:State>\n"
            + "    <ccr:PostalCode>17701</ccr:PostalCode>\n"
            + "   </ccr:Address>\n"
            + "   <ccr:Telephone>\n"
            + "    <ccr:Value>+1-301-975-3260</ccr:Value>\n"
            + "   </ccr:Telephone>\n"
            + "   <ccr:Source/>\n"
            + "  </ccr:Actor>\n"
            + "  <ccr:Actor>\n"
            + "   <ccr:ActorObjectID>RecipientID_01</ccr:ActorObjectID>\n"
            + "   <ccr:Person>\n"
            + "    <ccr:Name>\n"
            + "     <ccr:BirthName>\n"
            + "      <ccr:Given>Interested</ccr:Given>\n"
            + "      <ccr:Family>AnyPerson</ccr:Family>\n"
            + "     </ccr:BirthName>\n"
            + "    </ccr:Name>\n"
            + "   </ccr:Person>\n"
            + "   <ccr:Source/>\n"
            + "  </ccr:Actor>\n"
            + "  <ccr:Actor>\n"
            + "   <ccr:ActorObjectID>ManufID_1</ccr:ActorObjectID>\n"
            + "   <ccr:Organization>\n"
            + "    <ccr:Name>GLAXOSMITHKLINE</ccr:Name>\n"
            + "   </ccr:Organization>\n"
            + "   <ccr:Source/>\n"
            + "  </ccr:Actor>\n"
            + "  <ccr:Actor>\n"
            + "   <ccr:ActorObjectID>ManufID_2</ccr:ActorObjectID>\n"
            + "   <ccr:Organization>\n"
            + "    <ccr:Name>Merck</ccr:Name>\n"
            + "   </ccr:Organization>\n"
            + "   <ccr:Source/>\n"
            + "  </ccr:Actor>\n"
            + "  <ccr:Actor>\n"
            + "   <ccr:ActorObjectID>ClinicID_01</ccr:ActorObjectID>\n"
            + "   <ccr:Organization>\n"
            + "    <ccr:Name>Metropolitan Clinic</ccr:Name>\n"
            + "   </ccr:Organization>\n"
            + "   <ccr:Address>\n"
            + "    <ccr:Line1>5544 Sutter Street</ccr:Line1>\n"
            + "    <ccr:City>Williamsport</ccr:City>\n"
            + "    <ccr:State>PA</ccr:State>\n"
            + "    <ccr:PostalCode>17701</ccr:PostalCode>\n"
            + "   </ccr:Address>\n"
            + "   <ccr:Source/>\n"
            + "  </ccr:Actor>\n"
            + "   </ccr:Actors>\n"
            + "</ccr:ContinuityOfCareRecord>";

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) throws Exception {
        Stax_Test1 st = new Stax_Test1();
        st.parseCCDAStax(xmlString);
        st.parseCCDAStax(CCRString);
    }

    private void parseCCDAStax(String content) throws Exception {
        XMLInputFactory xmlInputFactory = XMLInputFactory.newInstance();
        XMLEventReader xmlEventReader = xmlInputFactory.createXMLEventReader(new StringReader(content));
        XMLStreamReader xmlStreamReader = xmlInputFactory.createXMLStreamReader(new StringReader(content));
        XMLOutputFactory factory = XMLOutputFactory.newInstance();
        XMLStreamWriter writer = factory.createXMLStreamWriter(new StringWriter());
        XMLEventFactory eventFactory = XMLEventFactory.newInstance();

        boolean stopProcessing = false;
        boolean xslFound = false;
        String localName="",prefix="";
        while (xmlStreamReader.hasNext() && !stopProcessing) {
            if (xmlStreamReader.getEventType() == XMLStreamConstants.START_ELEMENT
                    && ((xmlStreamReader.getLocalName().contains("ContinuityOfCareRecord")) ||
                    ( xmlStreamReader.getLocalName().contains("ClinicalDocument")))
                    ){
                localName=xmlStreamReader.getLocalName();
                prefix=xmlStreamReader.getPrefix();                                
                stopProcessing = true;
            }
            
            if (xmlStreamReader.getEventType() == XMLStreamConstants.PROCESSING_INSTRUCTION) {
                System.out.println("   xmlStreamReader.getPIData()   :" + xmlStreamReader.getPIData());
                System.out.println("   xmlStreamReader.getPITarget()   :" + xmlStreamReader.getPITarget());
                if (xmlStreamReader.getPIData().contains("type=\"text/xsl\"") && xmlStreamReader.getPITarget().contains("xml-stylesheet")) {
                    xslFound = true;
                }
                 stopProcessing = true;
            }
            xmlStreamReader.next();
        }

        xmlStreamReader.close();
        
        String stringToSearch="";
        if(prefix.length()>0)stringToSearch="<"+prefix+":"+localName;
        else stringToSearch="<"+localName;
        
        int index=content.indexOf(stringToSearch);

    }

    private static void printEvent(XMLStreamReader xmlr) {
        System.out.print("EVENT:[" + xmlr.getLocation().getLineNumber() + "]["
                + xmlr.getLocation().getColumnNumber() + "] ");
        System.out.print(" [");
        switch (xmlr.getEventType()) {
            case XMLStreamConstants.START_ELEMENT:
                System.out.print("<");
                printName(xmlr);
                printNamespaces(xmlr);
                printAttributes(xmlr);
                System.out.print(">");
                break;
            case XMLStreamConstants.END_ELEMENT:
                System.out.print("</");
                printName(xmlr);
                System.out.print(">");
                break;
            case XMLStreamConstants.SPACE:
            case XMLStreamConstants.CHARACTERS:
                int start = xmlr.getTextStart();
                int length = xmlr.getTextLength();
                System.out.print(new String(xmlr.getTextCharacters(),
                        start,
                        length));
                break;
            case XMLStreamConstants.PROCESSING_INSTRUCTION:
                System.out.print("<?");
                if (xmlr.hasText()) {
                    System.out.print(xmlr.getText());
                }
                System.out.print("?>");
                break;
            case XMLStreamConstants.CDATA:
                System.out.print("<![CDATA[");
                start = xmlr.getTextStart();
                length = xmlr.getTextLength();
                System.out.print(new String(xmlr.getTextCharacters(),
                        start,
                        length));
                System.out.print("]]>");
                break;
            case XMLStreamConstants.COMMENT:
                System.out.print("<!--");
                if (xmlr.hasText()) {
                    System.out.print(xmlr.getText());
                }
                System.out.print("-->");
                break;
            case XMLStreamConstants.ENTITY_REFERENCE:
                System.out.print(xmlr.getLocalName() + "=");
                if (xmlr.hasText()) {
                    System.out.print("[" + xmlr.getText() + "]");
                }
                break;
            case XMLStreamConstants.START_DOCUMENT:
                System.out.print("<?xml");
                System.out.print(" version='" + xmlr.getVersion() + "'");
                System.out.print(" encoding='" + xmlr.getCharacterEncodingScheme() + "'");
                if (xmlr.isStandalone()) {
                    System.out.print(" standalone='yes'");
                } else {
                    System.out.print(" standalone='no'");
                }
                System.out.print("?>");
                break;
        }
        System.out.println("]");
    }

    private static void printName(XMLStreamReader xmlr) {
        if (xmlr.hasName()) {
            String prefix = xmlr.getPrefix();
            String uri = xmlr.getNamespaceURI();
            String localName = xmlr.getLocalName();
            printName(prefix, uri, localName);
        }
    }

    private static void printName(String prefix,
            String uri,
            String localName) {
        if (uri != null && !("".equals(uri))) {
            System.out.print("['" + uri + "']:");
        }
        if (prefix != null) {
            System.out.print(prefix + ":");
        }
        if (localName != null) {
            System.out.print(localName);
        }
    }

    private static void printAttributes(XMLStreamReader xmlr) {
        for (int i = 0; i < xmlr.getAttributeCount(); i++) {
            printAttribute(xmlr, i);
        }
    }

    private static void printAttribute(XMLStreamReader xmlr, int index) {
        String prefix = xmlr.getAttributePrefix(index);
        String namespace = xmlr.getAttributeNamespace(index);
        String localName = xmlr.getAttributeLocalName(index);
        String value = xmlr.getAttributeValue(index);
        System.out.print(" ");
        printName(prefix, namespace, localName);
        System.out.print("='" + value + "'");
    }

    private static void printNamespaces(XMLStreamReader xmlr) {
        for (int i = 0; i < xmlr.getNamespaceCount(); i++) {
            printNamespace(xmlr, i);
        }
    }

    private static void printNamespace(XMLStreamReader xmlr, int index) {
        String prefix = xmlr.getNamespacePrefix(index);
        String uri = xmlr.getNamespaceURI(index);
        System.out.print(" ");
        if (prefix == null) {
            System.out.print("xmlns='" + uri + "'");
        } else {
            System.out.print("xmlns:" + prefix + "='" + uri + "'");
        }
    }
}
