/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stax;

import java.io.IOException;
import java.io.StringReader;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.SAXParser;
import javax.xml.parsers.SAXParserFactory;
import org.w3c.dom.Node;
import org.xml.sax.ErrorHandler;
import org.xml.sax.InputSource;
import org.xml.sax.SAXException;
import org.xml.sax.SAXParseException;
import org.xml.sax.XMLReader;

/**
 *
 * @author Ravi.Nistala
 */
public class XML_DOM_Test {
    private static final String head1="<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
"\n" +
"<!-- The following sample document depicts a fictional characters health summary. Any resemblance to a real person is coincidental. -->";
private static final String head="<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
"\n" 
+"<!-- The following sample document depicts a fictional characters health summary. Any resemblance to a real person is coincidental. -->"
        +"<?xml-stylesheet type=\"text/xsl\" href=\"CCD.xsl\"?> ";
private static final String head2="<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
"<?xml-stylesheet type=\"text/xsl\" href=\"CCD.xsl\"?> "
+"<!-- The following sample document depicts a fictional characters health summary. Any resemblance to a real person is coincidental. -->";
       
    private static final String xmlString = head2+"<ClinicalDocument>\n"
            + "  <typeId extension=\"POCD_HD000040\" root=\"2.16.840.1.113883.1.3\"/>\n"
            + "  <templateId assigningAuthorityName=\"CDA/R2\" root=\"2.16.840.1.113883.3.27.1776\"/>\n"
            + "  <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1\"/>\n"
            + "  <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.1\"/>\n"
            + "  <id extension=\"Laika C32 Test\" assigningAuthorityName=\"Laika: An Open Source EHR Testing Framework projectlaika.org\" root=\"2.16.840.1.113883.3.72\"/>\n"
            + "  <code code=\"34133-9\" displayName=\"Summarization of patient data\" codeSystemName=\"LOINC\" codeSystem=\"2.16.840.1.113883.6.1\"/>\n"
            + "  <title>VA WW TEF #1</title>\n"
            + "  <effectiveTime value=\"20080522100845-0500\"/>\n"
            + "  <confidentialityCode/>\n"
            + "  <languageCode code=\"en-US\"/>\n"
            + "  <recordTarget>\n"
            + "    <patientRole>\n"
            + "      <id extension=\"1234567890\"/>\n"
            + "      <addr>\n"
            + "        <streetAddressLine>1980 Aggrrttooff Court</streetAddressLine>\n"
            + "        <city>Dulles</city>\n"
            + "        <state>VA</state>\n"
            + "        <postalCode>20165</postalCode>\n"
            + "        <country>US</country>\n"
            + "      </addr>\n"
            + "      <telecom value=\"tel:703-555-3311\" use=\"HP\"/>\n"
            + "      <telecom value=\"tel:703-555-2332\" use=\"WP\"/>\n"
            + "      <telecom value=\"mailto:ca@yahoo.com\"/>\n"
            + "      <patient>\n"
            + "        <name>\n"
            + "          <prefix>Mr.</prefix>\n"
            + "          <given qualifier=\"CL\">Cxey</given>\n"
            + "          <family qualifier=\"BR\">Aaaactxy</family>\n"
            + "        </name>\n"
            + "        <administrativeGenderCode code=\"M\" displayName=\"Male\" codeSystemName=\"HL7 AdministrativeGenderCodes\" codeSystem=\"2.16.840.1.113883.5.1\">\n"
            + "          <originalText>AdministrativeGender codes are: M (Male), F (Female) or UN (Undifferentiated).</originalText>\n"
            + "        </administrativeGenderCode>\n"
            + "        <birthTime value=\"19800808\"/>\n"
            + "        <maritalStatusCode code=\"M\" displayName=\"Married\" codeSystemName=\"MaritalStatusCode\" codeSystem=\"2.16.840.1.113883.5.2\"/>\n"
            + "        <religiousAffiliationCode code=\"1013\" displayName=\"Christian\" codeSystemName=\"Religious Affiliation\" codeSystem=\"2.16.840.1.113883.5.1076\"/>\n"
            + "        <languageCommunication>\n"
            + "          <templateId root=\"2.16.840.1.113883.3.88.11.32.2\"/>\n"
            + "          <languageCode code=\"en-US\"/>\n"
            + "          <preferenceInd value=\"false\"/>\n"
            + "        </languageCommunication>\n"
            + "      </patient>\n"
            + "	  <providerOrganization>\n"
            + "				<id root=\"2.16.840.1.113883.1.13.99999\"/>\n"
            + "				<name>Local Community Hospital Organization-2</name>\n"
            + "				<telecom use=\"WP\" value=\"tel:(555) 555-1010\"/>\n"
            + "				<addr use=\"WP\">\n"
            + "					<streetAddressLine>4000 Hospital Dr.</streetAddressLine>\n"
            + "					<city>Portland</city>\n"
            + "					<state>OR</state>\n"
            + "					<postalCode>97005- </postalCode>\n"
            + "					<country>US</country>\n"
            + "				</addr>\n"
            + "			</providerOrganization>\n"
            + "    </patientRole>\n"
            + "  </recordTarget>\n"
            + "  <author>\n"
            + "    <time value=\"20080417\"/>\n"
            + "    <assignedAuthor>\n"
            + "      <id root=\"C320417200800000000001\"/>\n"
            + "      <assignedPerson>\n"
            + "        <name>\n"
            + "        </name>\n"
            + "      </assignedPerson>\n"
            + "      <representedOrganization>\n"
            + "        <id root=\"2.16.840.1.113883.19.5\"/>\n"
            + "        <name>Depertment of Veterans Affairs</name>\n"
            + "      </representedOrganization>\n"
            + "    </assignedAuthor>\n"
            + "  </author>\n"
            + "  <custodian>\n"
            + "    <assignedCustodian>\n"
            + "      <representedCustodianOrganization>\n"
            + "        <id/>\n"
            + "      </representedCustodianOrganization>\n"
            + "    </assignedCustodian>\n"
            + "  </custodian>\n"
            + "  <participant typeCode=\"IND\">\n"
            + "    <templateId root=\"2.16.840.1.113883.3.88.11.32.3\"/>\n"
            + "    <time>\n"
            + "      <low value=\"19990919\"/>\n"
            + "    </time>\n"
            + "    <associatedEntity classCode=\"NOK\">\n"
            + "      <code code=\"WIFE\" displayName=\"Wife\" codeSystemName=\"RoleCode\" codeSystem=\"2.16.840.1.113883.5.111\"/>\n"
            + "      <addr>\n"
            + "        <streetAddressLine>1980 Aggrrttooff Court</streetAddressLine>\n"
            + "        <city>Dulles</city>\n"
            + "        <state>VA</state>\n"
            + "        <postalCode>20165</postalCode>\n"
            + "        <country>US</country>\n"
            + "      </addr>\n"
            + "      <telecom value=\"tel:703-555-1980\" use=\"HP\"/>\n"
            + "      <telecom value=\"tel:703-555-4466\" use=\"WP\"/>\n"
            + "      <telecom value=\"mailto:wja@msn.com\"/>\n"
            + "      <associatedPerson>\n"
            + "        <name>\n"
            + "          <prefix>Mrs.</prefix>\n"
            + "          <given qualifier=\"CL\">Jikkklaan</given>\n"
            + "          <family qualifier=\"BR\">Aaaactxy</family>\n"
            + "        </name>\n"
            + "      </associatedPerson>\n"
            + "    </associatedEntity>\n"
            + "  </participant>\n"
            + "  <documentationOf>\n"
            + "    <serviceEvent classCode=\"PCPR\">\n"
            + "      <effectiveTime>\n"
            + "        <low value=\"0\"/>\n"
            + "        <high value=\"2010\"/>\n"
            + "      </effectiveTime>\n"
            + "      <performer typeCode=\"PRF\">\n"
            + "        <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.4\"/>\n"
            + "        <functionCode code=\"PP\" displayName=\"Primary Care Provider\" codeSystemName=\"Provider Role\" codeSystem=\"2.16.840.1.113883.12.443\">\n"
            + "        </functionCode>\n"
            + "        <time>\n"
            + "          <low value=\"19990707\"/>\n"
            + "        </time>\n"
            + "        <assignedEntity>\n"
            + "          <id/>\n"
            + "          <code code=\"320000000X\" displayName=\"Residential Treatment Facilities\" codeSystemName=\"ProviderCodes\" codeSystem=\"2.16.840.1.113883.6.101\"/>\n"
            + "          <addr>\n"
            + "            <streetAddressLine>5445 Rhhojjkk Blvd</streetAddressLine>\n"
            + "            <streetAddressLine>Suite #6789</streetAddressLine>\n"
            + "            <city>Dulles</city>\n"
            + "            <state>VA</state>\n"
            + "            <postalCode>20165</postalCode>\n"
            + "            <country>US</country>\n"
            + "          </addr>\n"
            + "          <telecom value=\"tel:703-555-8998\" use=\"WP\"/>\n"
            + "          <assignedPerson>\n"
            + "            <name>\n"
            + "              <prefix>Dr.</prefix>\n"
            + "              <given qualifier=\"CL\">Peppplrrr</given>\n"
            + "              <family qualifier=\"BR\">Wdssjhheeem</family>\n"
            + "            </name>\n"
            + "          </assignedPerson>\n"
            + "        </assignedEntity>\n"
            + "      </performer>\n"
            + "    </serviceEvent>\n"
            + "  </documentationOf>\n"
            + "  <component>\n"
            + "    <structuredBody>\n"
            + "      <component>\n"
            + "        <section>\n"
            + "          <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.11\"/>\n"
            + "          <code code=\"11450-4\" displayName=\"Problems\" codeSystemName=\"LOINC\" codeSystem=\"2.16.840.1.113883.6.1\"/>\n"
            + "          <title>Conditions or Problems</title>\n"
            + "          <text>\n"
            + "            <table border=\"1\" width=\"100%\">\n"
            + "              <thead>\n"
            + "                <tr>\n"
            + "                  <th>Problem Name</th>\n"
            + "                  <th>Problem Type</th>\n"
            + "                  <th>Problem Date</th>\n"
            + "                </tr>\n"
            + "              </thead>\n"
            + "              <tbody>\n"
            + "                <tr>\n"
            + "                  <td>\n"
            + "                    <content ID=\"problem-1021520673\">Patient complains of pain in the right foot.</content>\n"
            + "                  </td>\n"
            + "                  <td>Complaint</td>\n"
            + "                  <td>20080215</td>\n"
            + "                </tr>\n"
            + "                <tr>\n"
            + "                  <td>\n"
            + "                    <content ID=\"problem-1021520674\">some discoloration of the skin on right foot/2nd toe.</content>\n"
            + "                  </td>\n"
            + "                  <td>Finding</td>\n"
            + "                  <td>20080215</td>\n"
            + "                </tr>\n"
            + "                <tr>\n"
            + "                  <td>\n"
            + "                    <content ID=\"problem-1021520675\">Roadsie bomb injury.</content>\n"
            + "                  </td>\n"
            + "                  <td>Problem</td>\n"
            + "                  <td>20060101</td>\n"
            + "                </tr>\n"
            + "                <tr>\n"
            + "                  <td>\n"
            + "                    <content ID=\"problem-1021520676\">Prior surgeries to the right leg occurred at several Army Medical Treatment Facilities for shrapnel removal.</content>\n"
            + "                  </td>\n"
            + "                  <td>Finding</td>\n"
            + "                  <td>20060101</td>\n"
            + "                </tr>\n"
            + "                <tr>\n"
            + "                  <td>\n"
            + "                    <content ID=\"problem-1021520677\">X-ray of the right foot shows a radio-opaque fragment overlying the distal 2nd metatarsal bone</content>\n"
            + "                  </td>\n"
            + "                  <td>Finding</td>\n"
            + "                  <td>20080215</td>\n"
            + "                </tr>\n"
            + "                <tr>\n"
            + "                  <td>\n"
            + "                    <content ID=\"problem-1021520678\">309.81-Posttraumatic stress disorder</content>\n"
            + "                  </td>\n"
            + "                  <td>Diagnosis</td>\n"
            + "                  <td>20060101</td>\n"
            + "                </tr>\n"
            + "                <tr>\n"
            + "                  <td>\n"
            + "                    <content ID=\"problem-1021520679\">Surgery advised for collection of the fragment, surrounding tissue and lavage fluid</content>\n"
            + "                  </td>\n"
            + "                  <td>Finding</td>\n"
            + "                  <td>20080217</td>\n"
            + "                </tr>\n"
            + "                <tr>\n"
            + "                  <td>\n"
            + "                    <content ID=\"problem-1021520680\">CPT 20520-Removal of foreign body in muscle or tendon sheath; simple</content>\n"
            + "                  </td>\n"
            + "                  <td>Condition</td>\n"
            + "                  <td>20080307</td>\n"
            + "                </tr>\n"
            + "                <tr>\n"
            + "                  <td>\n"
            + "                    <content ID=\"problem-1021520681\">Urine bio-monitoring kit recommended for home use.</content>\n"
            + "                  </td>\n"
            + "                  <td>Finding</td>\n"
            + "                  <td>20080403</td>\n"
            + "                </tr>\n"
            + "                <tr>\n"
            + "                  <td>\n"
            + "                    <content ID=\"problem-1021520682\">401.1-Hypertension</content>\n"
            + "                  </td>\n"
            + "                  <td>Diagnosis</td>\n"
            + "                  <td>20060101</td>\n"
            + "                </tr>\n"
            + "                <tr>\n"
            + "                  <td>\n"
            + "                    <content ID=\"problem-1021520683\">Foot lump dorsum of the foot just below the 2nd toe</content>\n"
            + "                  </td>\n"
            + "                  <td>Symptom</td>\n"
            + "                  <td>20080215</td>\n"
            + "                </tr>\n"
            + "                <tr>\n"
            + "                  <td>\n"
            + "                    <content ID=\"problem-1021520684\">URINE  Heavy Metal:  Fe 25mg/24h, CU 0.03mg/24h, Pb 0.2mg/24h</content>\n"
            + "                  </td>\n"
            + "                  <td>Finding</td>\n"
            + "                  <td>20080615</td>\n"
            + "                </tr>\n"
            + "              </tbody>\n"
            + "            </table>\n"
            + "          </text>\n"
            + "          <entry>\n"
            + "            <act classCode=\"ACT\" moodCode=\"EVN\">\n"
            + "              <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.27\"/>\n"
            + "              <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.7\"/>\n"
            + "              <id/>\n"
            + "              <code nullFlavor=\"NA\"/>\n"
            + "              <effectiveTime>\n"
            + "                <low value=\"20080215\"/>\n"
            + "                <high nullFlavor=\"UNK\"/>\n"
            + "              </effectiveTime>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.28\"/>\n"
            + "                  <code code=\"409586006\" displayName=\"Complaint\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <text>\n"
            + "                    <reference value=\"#problem-1021520673\"/>\n"
            + "                  </text>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </act>\n"
            + "          </entry>\n"
            + "          <entry>\n"
            + "            <act classCode=\"ACT\" moodCode=\"EVN\">\n"
            + "              <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.27\"/>\n"
            + "              <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.7\"/>\n"
            + "              <id/>\n"
            + "              <code nullFlavor=\"NA\"/>\n"
            + "              <effectiveTime>\n"
            + "                <low value=\"20080215\"/>\n"
            + "                <high nullFlavor=\"UNK\"/>\n"
            + "              </effectiveTime>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.28\"/>\n"
            + "                  <code code=\"404684003\" displayName=\"Finding\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <text>\n"
            + "                    <reference value=\"#problem-1021520674\"/>\n"
            + "                  </text>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </act>\n"
            + "          </entry>\n"
            + "          <entry>\n"
            + "            <act classCode=\"ACT\" moodCode=\"EVN\">\n"
            + "              <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.27\"/>\n"
            + "              <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.7\"/>\n"
            + "              <id/>\n"
            + "              <code nullFlavor=\"NA\"/>\n"
            + "              <effectiveTime>\n"
            + "                <low value=\"20060101\"/>\n"
            + "                <high nullFlavor=\"UNK\"/>\n"
            + "              </effectiveTime>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.28\"/>\n"
            + "                  <code code=\"55607006\" displayName=\"Problem\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <text>\n"
            + "                    <reference value=\"#problem-1021520675\"/>\n"
            + "                  </text>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </act>\n"
            + "          </entry>\n"
            + "          <entry>\n"
            + "            <act classCode=\"ACT\" moodCode=\"EVN\">\n"
            + "              <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.27\"/>\n"
            + "              <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.7\"/>\n"
            + "              <id/>\n"
            + "              <code nullFlavor=\"NA\"/>\n"
            + "              <effectiveTime>\n"
            + "                <low value=\"20060101\"/>\n"
            + "                <high nullFlavor=\"UNK\"/>\n"
            + "              </effectiveTime>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.28\"/>\n"
            + "                  <code code=\"404684003\" displayName=\"Finding\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <text>\n"
            + "                    <reference value=\"#problem-1021520676\"/>\n"
            + "                  </text>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </act>\n"
            + "          </entry>\n"
            + "          <entry>\n"
            + "            <act classCode=\"ACT\" moodCode=\"EVN\">\n"
            + "              <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.27\"/>\n"
            + "              <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.7\"/>\n"
            + "              <id/>\n"
            + "              <code nullFlavor=\"NA\"/>\n"
            + "              <effectiveTime>\n"
            + "                <low value=\"20080215\"/>\n"
            + "                <high nullFlavor=\"UNK\"/>\n"
            + "              </effectiveTime>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.28\"/>\n"
            + "                  <code code=\"404684003\" displayName=\"Finding\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <text>\n"
            + "                    <reference value=\"#problem-1021520677\"/>\n"
            + "                  </text>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </act>\n"
            + "          </entry>\n"
            + "          <entry>\n"
            + "            <act classCode=\"ACT\" moodCode=\"EVN\">\n"
            + "              <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.27\"/>\n"
            + "              <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.7\"/>\n"
            + "              <id/>\n"
            + "              <code nullFlavor=\"NA\"/>\n"
            + "              <effectiveTime>\n"
            + "                <low value=\"20060101\"/>\n"
            + "                <high nullFlavor=\"UNK\"/>\n"
            + "              </effectiveTime>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.28\"/>\n"
            + "                  <code code=\"282291009\" displayName=\"Diagnosis\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <text>\n"
            + "                    <reference value=\"#problem-1021520678\"/>\n"
            + "                  </text>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </act>\n"
            + "          </entry>\n"
            + "          <entry>\n"
            + "            <act classCode=\"ACT\" moodCode=\"EVN\">\n"
            + "              <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.27\"/>\n"
            + "              <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.7\"/>\n"
            + "              <id/>\n"
            + "              <code nullFlavor=\"NA\"/>\n"
            + "              <effectiveTime>\n"
            + "                <low value=\"20080217\"/>\n"
            + "                <high nullFlavor=\"UNK\"/>\n"
            + "              </effectiveTime>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.28\"/>\n"
            + "                  <code code=\"404684003\" displayName=\"Finding\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <text>\n"
            + "                    <reference value=\"#problem-1021520679\"/>\n"
            + "                  </text>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </act>\n"
            + "          </entry>\n"
            + "          <entry>\n"
            + "            <act classCode=\"ACT\" moodCode=\"EVN\">\n"
            + "              <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.27\"/>\n"
            + "              <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.7\"/>\n"
            + "              <id/>\n"
            + "              <code nullFlavor=\"NA\"/>\n"
            + "              <effectiveTime>\n"
            + "                <low value=\"20080307\"/>\n"
            + "                <high nullFlavor=\"UNK\"/>\n"
            + "              </effectiveTime>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.28\"/>\n"
            + "                  <code code=\"64572001\" displayName=\"Condition\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <text>\n"
            + "                    <reference value=\"#problem-1021520680\"/>\n"
            + "                  </text>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </act>\n"
            + "          </entry>\n"
            + "          <entry>\n"
            + "            <act classCode=\"ACT\" moodCode=\"EVN\">\n"
            + "              <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.27\"/>\n"
            + "              <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.7\"/>\n"
            + "              <id/>\n"
            + "              <code nullFlavor=\"NA\"/>\n"
            + "              <effectiveTime>\n"
            + "                <low value=\"20080403\"/>\n"
            + "                <high nullFlavor=\"UNK\"/>\n"
            + "              </effectiveTime>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.28\"/>\n"
            + "                  <code code=\"404684003\" displayName=\"Finding\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <text>\n"
            + "                    <reference value=\"#problem-1021520681\"/>\n"
            + "                  </text>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </act>\n"
            + "          </entry>\n"
            + "          <entry>\n"
            + "            <act classCode=\"ACT\" moodCode=\"EVN\">\n"
            + "              <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.27\"/>\n"
            + "              <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.7\"/>\n"
            + "              <id/>\n"
            + "              <code nullFlavor=\"NA\"/>\n"
            + "              <effectiveTime>\n"
            + "                <low value=\"20060101\"/>\n"
            + "                <high nullFlavor=\"UNK\"/>\n"
            + "              </effectiveTime>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.28\"/>\n"
            + "                  <code code=\"282291009\" displayName=\"Diagnosis\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <text>\n"
            + "                    <reference value=\"#problem-1021520682\"/>\n"
            + "                  </text>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </act>\n"
            + "          </entry>\n"
            + "          <entry>\n"
            + "            <act classCode=\"ACT\" moodCode=\"EVN\">\n"
            + "              <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.27\"/>\n"
            + "              <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.7\"/>\n"
            + "              <id/>\n"
            + "              <code nullFlavor=\"NA\"/>\n"
            + "              <effectiveTime>\n"
            + "                <low value=\"20080215\"/>\n"
            + "                <high nullFlavor=\"UNK\"/>\n"
            + "              </effectiveTime>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.28\"/>\n"
            + "                  <code code=\"418799008\" displayName=\"Symptom\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <text>\n"
            + "                    <reference value=\"#problem-1021520683\"/>\n"
            + "                  </text>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </act>\n"
            + "          </entry>\n"
            + "          <entry>\n"
            + "            <act classCode=\"ACT\" moodCode=\"EVN\">\n"
            + "              <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.27\"/>\n"
            + "              <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.7\"/>\n"
            + "              <id/>\n"
            + "              <code nullFlavor=\"NA\"/>\n"
            + "              <effectiveTime>\n"
            + "                <low value=\"20080615\"/>\n"
            + "                <high nullFlavor=\"UNK\"/>\n"
            + "              </effectiveTime>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.28\"/>\n"
            + "                  <code code=\"404684003\" displayName=\"Finding\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <text>\n"
            + "                    <reference value=\"#problem-1021520684\"/>\n"
            + "                  </text>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </act>\n"
            + "          </entry>\n"
            + "        </section>\n"
            + "      </component>\n"
            + "      <component>\n"
            + "        <section>\n"
            + "          <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.2\"/>\n"
            + "          <code code=\"48765-2\" codeSystem=\"2.16.840.1.113883.6.1\"/>\n"
            + "          <title>Allergies, Adverse Reactions, Alerts</title>\n"
            + "          <text>\n"
            + "            <table border=\"1\" width=\"100%\">\n"
            + "              <thead>\n"
            + "                <tr>\n"
            + "                  <th>Substance</th>\n"
            + "                  <th>Event Type</th>\n"
            + "                  <th>Severity</th>\n"
            + "                </tr>\n"
            + "              </thead>\n"
            + "              <tbody>\n"
            + "                <tr>\n"
            + "                  <td>Lactose</td>\n"
            + "                  <td>Food Allergy</td>\n"
            + "                  <td>\n"
            + "                    <content ID=\"severity-823358887\">Mild</content>\n"
            + "                  </td>\n"
            + "                </tr>\n"
            + "                <tr>\n"
            + "                  <td>Penicillin</td>\n"
            + "                  <td>Drug Allergy</td>\n"
            + "                  <td/>\n"
            + "                </tr>\n"
            + "              </tbody>\n"
            + "            </table>\n"
            + "          </text>\n"
            + "          <entry>\n"
            + "            <act classCode=\"ACT\" moodCode=\"EVN\">\n"
            + "              <templateId root=\"2.16.840.1.113883.10.20.1.27\"/>\n"
            + "              <templateId root=\"2.16.840.1.113883.3.88.11.32.6\"/>\n"
            + "              <id root=\"2C748172-7CC2-4902-8AF0-23A105C4401B\"/>\n"
            + "              <code nullFlavor=\"NA\"/>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId root=\"2.16.840.1.113883.10.20.1.18\"/>\n"
            + "                  <code code=\"414285001\" displayName=\"Food Allergy\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                  <effectiveTime>\n"
            + "                    <low value=\"20061010\"/>\n"
            + "                    <high nullFlavor=\"UNK\"/>\n"
            + "                  </effectiveTime>\n"
            + "                  <participant typeCode=\"CSM\">\n"
            + "                    <participantRole classCode=\"MANU\">\n"
            + "                      <playingEntity classCode=\"MMAT\">\n"
            + "                        <code code=\"\" displayName=\"Lactose\" codeSystemName=\"RxNorm\" codeSystem=\"2.16.840.1.113883.6.88\"/>\n"
            + "                        <name>Lactose</name>\n"
            + "                      </playingEntity>\n"
            + "                    </participantRole>\n"
            + "                  </participant>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </act>\n"
            + "          </entry>\n"
            + "          <entry>\n"
            + "            <act classCode=\"ACT\" moodCode=\"EVN\">\n"
            + "              <templateId root=\"2.16.840.1.113883.10.20.1.27\"/>\n"
            + "              <templateId root=\"2.16.840.1.113883.3.88.11.32.6\"/>\n"
            + "              <id root=\"2C748172-7CC2-4902-8AF0-23A105C4401B\"/>\n"
            + "              <code nullFlavor=\"NA\"/>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId root=\"2.16.840.1.113883.10.20.1.18\"/>\n"
            + "                  <code code=\"416098002\" displayName=\"Drug Allergy\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                  <effectiveTime>\n"
            + "                    <low value=\"19901215\"/>\n"
            + "                    <high nullFlavor=\"UNK\"/>\n"
            + "                  </effectiveTime>\n"
            + "                  <participant typeCode=\"CSM\">\n"
            + "                    <participantRole classCode=\"MANU\">\n"
            + "                      <playingEntity classCode=\"MMAT\">\n"
            + "                        <code code=\"\" displayName=\"Penicillin\" codeSystemName=\"RxNorm\" codeSystem=\"2.16.840.1.113883.6.88\"/>\n"
            + "                        <name>Penicillin</name>\n"
            + "                      </playingEntity>\n"
            + "                    </participantRole>\n"
            + "                  </participant>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </act>\n"
            + "          </entry>\n"
            + "        </section>\n"
            + "      </component>\n"
            + "      <component>\n"
            + "        <section>\n"
            + "          <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.8\"/>\n"
            + "          <code code=\"10160-0\" displayName=\"History of medication use\" codeSystemName=\"LOINC\" codeSystem=\"2.16.840.1.113883.6.1\"/>\n"
            + "          <title>Medications</title>\n"
            + "          <text>\n"
            + "            <table border=\"1\" width=\"100%\">\n"
            + "              <thead>\n"
            + "                <tr>\n"
            + "                  <th>Product Display Name</th>\n"
            + "                  <th>Free Text Brand Name</th>\n"
            + "                  <th>Ordered Value</th>\n"
            + "                  <th>Ordered Unit</th>\n"
            + "                  <th>Expiration Time</th>\n"
            + "                </tr>\n"
            + "              </thead>\n"
            + "              <tbody>\n"
            + "                <tr>\n"
            + "                  <td>\n"
            + "                    <content ID=\"medication-809983340\">Quetiapine 25MG</content>\n"
            + "                  </td>\n"
            + "                  <td/>\n"
            + "                  <td/>\n"
            + "                  <td/>\n"
            + "                  <td/>\n"
            + "                </tr>\n"
            + "                <tr>\n"
            + "                  <td>\n"
            + "                    <content ID=\"medication-809983341\">Lisinopril 20MG</content>\n"
            + "                  </td>\n"
            + "                  <td/>\n"
            + "                  <td/>\n"
            + "                  <td/>\n"
            + "                  <td/>\n"
            + "                </tr>\n"
            + "                <tr>\n"
            + "                  <td>\n"
            + "                    <content ID=\"medication-809983342\">Sertraline 50MG</content>\n"
            + "                  </td>\n"
            + "                  <td/>\n"
            + "                  <td/>\n"
            + "                  <td/>\n"
            + "                  <td/>\n"
            + "                </tr>\n"
            + "              </tbody>\n"
            + "            </table>\n"
            + "          </text>\n"
            + "          <entry>\n"
            + "            <substanceAdministration classCode=\"SBADM\" moodCode=\"EVN\">\n"
            + "              <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.24\"/>\n"
            + "              <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.8\"/>\n"
            + "              <id/>\n"
            + "              <consumable>\n"
            + "                <manufacturedProduct classCode=\"MANU\">\n"
            + "                  <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.53\"/>\n"
            + "                  <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.9\"/>\n"
            + "                  <manufacturedMaterial classCode=\"MMAT\" determinerCode=\"KIND\">\n"
            + "                  </manufacturedMaterial>\n"
            + "                </manufacturedProduct>\n"
            + "              </consumable>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId root=\"2.16.840.1.113883.3.88.11.32.10\"/>\n"
            + "                  <code code=\"73639000\" displayName=\"Prescription Drug\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </substanceAdministration>\n"
            + "          </entry>\n"
            + "          <entry>\n"
            + "            <substanceAdministration classCode=\"SBADM\" moodCode=\"EVN\">\n"
            + "              <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.24\"/>\n"
            + "              <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.8\"/>\n"
            + "              <id/>\n"
            + "              <consumable>\n"
            + "                <manufacturedProduct classCode=\"MANU\">\n"
            + "                  <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.53\"/>\n"
            + "                  <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.9\"/>\n"
            + "                  <manufacturedMaterial classCode=\"MMAT\" determinerCode=\"KIND\">\n"
            + "                  </manufacturedMaterial>\n"
            + "                </manufacturedProduct>\n"
            + "              </consumable>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId root=\"2.16.840.1.113883.3.88.11.32.10\"/>\n"
            + "                  <code code=\"73639000\" displayName=\"Prescription Drug\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </substanceAdministration>\n"
            + "          </entry>\n"
            + "          <entry>\n"
            + "            <substanceAdministration classCode=\"SBADM\" moodCode=\"EVN\">\n"
            + "              <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.24\"/>\n"
            + "              <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.8\"/>\n"
            + "              <id/>\n"
            + "              <consumable>\n"
            + "                <manufacturedProduct classCode=\"MANU\">\n"
            + "                  <templateId assigningAuthorityName=\"CCD\" root=\"2.16.840.1.113883.10.20.1.53\"/>\n"
            + "                  <templateId assigningAuthorityName=\"HITSP/C32\" root=\"2.16.840.1.113883.3.88.11.32.9\"/>\n"
            + "                  <manufacturedMaterial classCode=\"MMAT\" determinerCode=\"KIND\">\n"
            + "                  </manufacturedMaterial>\n"
            + "                </manufacturedProduct>\n"
            + "              </consumable>\n"
            + "              <entryRelationship typeCode=\"SUBJ\">\n"
            + "                <observation classCode=\"OBS\" moodCode=\"EVN\">\n"
            + "                  <templateId root=\"2.16.840.1.113883.3.88.11.32.10\"/>\n"
            + "                  <code code=\"73639000\" displayName=\"Prescription Drug\" codeSystemName=\"SNOMED CT\" codeSystem=\"2.16.840.1.113883.6.96\"/>\n"
            + "                  <statusCode code=\"completed\"/>\n"
            + "                </observation>\n"
            + "              </entryRelationship>\n"
            + "            </substanceAdministration>\n"
            + "          </entry>\n"
            + "        </section>\n"
            + "      </component>\n"
            + "    </structuredBody>\n"
            + "  </component>\n"
            + "</ClinicalDocument>";

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {

        XML_DOM_Test st = new XML_DOM_Test();
        //st.verifyXML(xmlString);
        st.parseCCDA_DOM(xmlString);

    }

    private void verifyXML(String content) {
        try {
            SAXParserFactory factory = SAXParserFactory.newInstance();
            factory.setValidating(false);
            factory.setNamespaceAware(true);

            SAXParser parser = factory.newSAXParser();

            XMLReader reader = parser.getXMLReader();
            reader.setErrorHandler(new SimpleErrorHandler());
            reader.parse(new InputSource(new StringReader(content)));

            System.out.println("  Parsing Successfull ");
        } catch (Exception e) {
            System.out.println("  Exception  : "+e.getMessage());
        }
    }

    private class SimpleErrorHandler implements ErrorHandler {

        public void warning(SAXParseException e) throws SAXException {
            System.out.println("warning : "+e.getMessage());
        }

        public void error(SAXParseException e) throws SAXException {
            System.out.println(" error:  "+e.getMessage());
        }

        public void fatalError(SAXParseException e) throws SAXException {
            System.out.println(" fatalError :  "+e.getMessage());
        }
    }

    
     private  void parseCCDA_DOM(String ccda) {
        try {
            System.out.println("### In parseCCDA  ");
            DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
             Node doc = dBuilder.parse(new InputSource(new StringReader(ccda)));
           
            System.out.println("   findXSLNode(doc)   :"+findXSLNode(doc));
        } catch (Exception e) {
             System.out.println(" Error in XML parsing " + e.getMessage());
        }

    }
     
      private  boolean findXSLNode(Node node)throws IOException{
        Node tempNode=node;
        boolean xslFound=false;
        boolean stopLoop=false;
       while(!stopLoop){
        System.out.println(" ******************      tempNode.getNodeName()  :    "+tempNode.getNodeName());        
        System.out.println(" ^^^^^^^^^^^^^^^^^^^^^^  tempNode.getNodeValue()  :    "+tempNode.getNodeValue());        
        // pp.writeNode(node);
        if("Processing Instruction".equals(NodeTyper.getTypeName(tempNode)) 
                && "xml-stylesheet".equalsIgnoreCase(tempNode.getNodeName()) 
                        && tempNode.getNodeValue().contains("type=\"text/xsl\"")){
             System.out.println(" In findXSLNode- XSL Found  : "+tempNode.getNodeValue());
            xslFound= true;       
            stopLoop=true;
        }
       if("Element".equals(NodeTyper.getTypeName(tempNode)) 
                && "ClinicalDocument".equalsIgnoreCase(tempNode.getNodeName())){
            System.out.println(" In findXSLNode-  CliicalDocument node reched. Not found XSL");
            xslFound= false;       
            stopLoop=true;
        }
        
       if(tempNode.hasChildNodes()){
            System.out.println("   111111   ");
            Node firstChild=tempNode.getFirstChild();
            tempNode = firstChild;            
        }else{        
       
        Node nextNode=tempNode.getNextSibling();        
        if(nextNode!=null){System.out.println(" 22222222 ");tempNode = nextNode;}
       }
       }
        return xslFound;
    }
  
}
